package com.veltrix.hom.vnext.server

import kotlinx.serialization.Serializable

@Serializable
data class ErrorBody(val code: String, val category: String, val message: String, val retryable: Boolean, val requestId: String? = null)
@Serializable data class ErrorEnvelope(val error: ErrorBody)
@Serializable data class HealthResponse(val status: String, val service: String, val environment: String, val version: String)
@Serializable data class ReadinessResponse(val ready: Boolean, val database: String, val aiConfigured: Boolean, val testAiConfigured: Boolean = false, val storageConfigured: Boolean = false, val embeddingConfigured: Boolean = false)

@Serializable data class RegisterRequest(val login: String, val password: String, val displayName: String, val preferredLanguage: String = "en", val timezone: String = "UTC")
@Serializable data class LoginRequest(val login: String, val password: String, val deviceLabel: String? = null)
@Serializable data class SessionResponse(val sessionToken: String, val accountId: String, val expiresAt: String)
@Serializable data class GoogleIdentityExchangeRequest(val idToken:String,val nonce:String)
@Serializable data class ProfileResponse(val accountId: String, val displayName: String, val username: String?, val preferredLanguage: String, val timezone: String, val onboardingComplete: Boolean, val memoryEnabled: Boolean, val revision: Long)
@Serializable data class UpdateProfileRequest(val displayName: String? = null, val preferredLanguage: String? = null, val timezone: String? = null, val onboardingComplete: Boolean? = null, val memoryEnabled: Boolean? = null, val expectedRevision: Long)

@Serializable data class CreateProjectRequest(val title: String, val purpose: String? = null, val template: String = "CUSTOM", val priority: Int = 0)
@Serializable data class UpdateProjectRequest(val title: String? = null, val purpose: String? = null, val status: String? = null, val priority: Int? = null, val aiInstruction: String? = null, val expectedRevision: Long)
@Serializable data class ProjectResponse(val id: String, val title: String, val purpose: String?, val template: String, val priority: Int, val status: String, val aiInstruction: String?, val revision: Long, val updatedAt: String, val lastActiveAt: String)
@Serializable data class CreateGoalRequest(val title: String, val description: String? = null, val priority: Int = 0)
@Serializable data class GoalResponse(val id: String, val projectId: String, val title: String, val description: String?, val priority: Int, val status: String, val revision: Long, val completedAt: String?)

@Serializable data class MemoryCreateRequest(val scope: String, val scopeId: String? = null, val category: String, val statement: String, val origin: String, val confidence: Double, val evidenceKind: String, val evidenceObjectId: String)
@Serializable data class MemoryResponse(val id: String, val scope: String, val scopeId: String?, val category: String, val statement: String, val origin: String, val confidence: Double, val status: String, val revision: Long)
@Serializable data class MemoryMaturityResponse(val score: Int, val state: String)

@Serializable data class SourceCreateRequest(val title: String, val type: String, val mimeType: String, val contentHash: String, val sizeBytes: Long = 0)
@Serializable data class SourceResponse(val id: String, val title: String, val type: String, val mimeType: String, val contentHash: String, val state: String, val processingProgress: Int, val revision: Long)
@Serializable data class SourceSearchRequest(val query: String, val sourceIds: List<String> = emptyList(), val limit: Int = 8)
@Serializable data class CitationResponse(val sourceId: String, val sourceVersion: Long, val chunkId: String, val page: Int?, val section: String?, val relevance: Double, val textHash: String, val excerpt: String)

@Serializable data class SearchRequest(val query: String, val projectId: String? = null, val limit: Int = 30)
@Serializable data class SearchResultResponse(val type: String, val id: String, val title: String, val snippet: String, val projectId: String?, val score: Double, val deepLink: String)

@Serializable data class HomeSnapshotResponse(val accountId: String, val displayName: String, val defaultAvatarId: String, val recentProjects: List<ProjectResponse>, val currentFocus: String?, val memoryMaturity: String, val mapState: String, val unreadNotificationCount: Int, val syncState: String, val schemaVersion: Int, val level:Int=1, val lifetimeXp:Long=0, val coinBalance:Long=0, val currentConsistency:Int=0, val currentSeasonId:String?=null, val gameRevision:Long=0)

@Serializable data class AiStreamRequest(val conversationId: String, val projectId: String? = null, val sourceIds: List<String> = emptyList(), val attachmentIds: List<String> = emptyList(), val text: String, val learningMode: String = "DEFAULT", val memoryEnabled: Boolean = true, val projectMemoryEnabled: Boolean = true, val toolIds: List<String> = emptyList(), val toolInputs: Map<String,Map<String,String>> = emptyMap(), val originFeature: String? = null, val idempotencyKey: String)
@Serializable data class AiStreamEvent(val type: String, val messageId: String? = null, val segment: String? = null, val error: ErrorBody? = null, val final: Boolean = false)

@Serializable data class CreateConversationRequest(val scope: String = "GLOBAL", val projectId: String? = null, val title: String = "New chat", val learningMode: String = "DEFAULT", val memoryEnabled: Boolean = true, val projectMemoryEnabled: Boolean = true)
@Serializable data class ConversationResponse(val id: String, val projectId: String?, val scope: String, val title: String, val learningMode: String, val memoryEnabled: Boolean, val projectMemoryEnabled: Boolean, val pinned: Boolean, val archived: Boolean, val revision: Long, val updatedAt: String)
@Serializable data class SendMessageRequest(val text: String, val parentMessageId: String? = null, val branchKey: String? = null, val idempotencyKey: String)
@Serializable data class MessageResponse(val id: String, val conversationId: String, val parentMessageId: String?, val branchKey: String?, val role: String, val state: String, val content: String, val finalMarker: Boolean, val revision: Long, val createdAt: String, val updatedAt: String)

@Serializable data class CreateNoteRequest(val title: String, val body: String, val projectId: String? = null, val sourceId: String? = null, val conversationId: String? = null)
@Serializable data class UpdateNoteRequest(val title: String? = null, val body: String? = null, val pinned: Boolean? = null, val archived: Boolean? = null, val expectedRevision: Long)
@Serializable data class NoteResponse(val id: String, val projectId: String?, val sourceId: String?, val conversationId: String?, val title: String, val body: String, val pinned: Boolean, val archived: Boolean, val revision: Long, val updatedAt: String)

@Serializable data class QuestionRequest(val prompt: String, val type: String, val options: List<String> = emptyList(), val expectedAnswers: List<String>, val numericTolerance: Double? = null, val evidence: List<CitationResponse> = emptyList())
@Serializable data class CreateAssessmentRequest(val kind: String, val title: String, val projectId: String? = null, val questions: List<QuestionRequest>)
@Serializable data class AssessmentResponse(val id: String, val kind: String, val title: String, val projectId: String?, val state: String, val questionCount: Int, val revision: Long)
@Serializable data class AttemptResponse(val id: String, val assessmentId: String, val projectId: String?, val state: String, val score: Double?, val revision: Long)
@Serializable data class SaveAnswerRequest(val questionId: String, val answers: List<String>)
@Serializable data class SubmitAttemptResponse(val attempt: AttemptResponse, val score: Double, val accuracy: Double, val incorrectQuestionIds: List<String>, val mistakeIds: List<String>)

@Serializable data class CreatePracticeRequest(val projectId: String? = null, val focusTopic: String? = null, val targetMistakeId: String? = null)
@Serializable data class PracticeResponse(val id: String, val projectId: String?, val focusTopic: String?, val targetMistakeId: String?, val state: String, val revision: Long)

@Serializable data class CreateDeckRequest(val title: String, val scope: String = "GLOBAL", val projectId: String? = null, val sourceId: String? = null)
@Serializable data class DeckResponse(val id: String, val title: String, val scope: String, val projectId: String?, val sourceId: String?, val revision: Long)
@Serializable data class CreateCardRequest(val front: String, val back: String, val explanation: String? = null, val projectId: String? = null)
@Serializable data class CardResponse(val id: String, val deckId: String, val projectId: String?, val front: String, val back: String, val explanation: String?, val dueAt: String, val intervalDays: Int, val repetitions: Int, val lapses: Int, val revision: Long)
@Serializable data class ReviewCardRequest(val rating: String)

@Serializable data class MistakeResponse(val id: String, val projectId: String?, val sourceId: String?, val topic: String, val prompt: String, val userAnswer: String?, val expectedAnswer: String?, val occurrenceCount: Int, val status: String, val revision: Long)
@Serializable data class TranslationRequest(val text: String, val targetLanguage: String, val sourceLanguage: String? = null, val projectId: String? = null)
@Serializable data class ToolRequest(val toolId: String, val input: Map<String, String>, val conversationId: String? = null, val projectId: String? = null)
@Serializable data class ToolResponse(val toolId: String, val output: Map<String, String>, val deterministic: Boolean)
@Serializable data class ProjectWorkspaceResponse(val project: ProjectResponse, val goals: List<GoalResponse>, val recentChats: List<ConversationResponse>, val sourceCount: Int, val noteCount: Int, val assessmentCount: Int, val flashcardCount: Int, val mistakeCount: Int, val memoryMaturity: String, val schemaVersion: Int = 1)
@Serializable data class GoalTransitionRequest(val target: String, val expectedRevision: Long)
@Serializable data class SourceTextIngestRequest(val text: String)
@Serializable data class ProjectLinkRequest(val projectId: String)
@Serializable data class MemoryCorrectionRequest(val statement: String, val evidenceObjectId: String)
@Serializable data class CompletePracticeRequest(val expectedRevision: Long)
@Serializable data class ResolveMistakeRequest(val expectedRevision: Long)
@Serializable data class ApiAck(val ok: Boolean = true)

@Serializable data class SettingPutRequest(val category:String,val key:String,val jsonValue:String)
@Serializable data class SettingResponse(val category:String,val key:String,val jsonValue:String,val revision:Long,val updatedAt:String)
@Serializable data class NotificationPreferencePutRequest(val category:String,val enabled:Boolean,val quietHoursJson:String="{}",val timezone:String="UTC")
@Serializable data class NotificationPreferenceResponse(val category:String,val enabled:Boolean,val quietHoursJson:String,val timezone:String,val revision:Long,val updatedAt:String)
@Serializable data class NotificationIntentResponse(val id:String,val projectId:String?,val category:String,val payloadJson:String,val scheduledFor:String?,val status:String,val createdAt:String)
@Serializable data class LearningModeResponse(val id:String,val answerDepth:String,val guidingQuestions:Boolean,val revealAnswersImmediately:Boolean,val citationPreference:String,val correctionStyle:String)
@Serializable data class AccountExportProfile(val displayName:String,val preferredLanguage:String,val timezone:String,val onboardingComplete:Boolean,val memoryEnabled:Boolean)
@Serializable data class AccountExportResponse(val accountId:String,val generatedAt:String,val profile:AccountExportProfile,val entityCounts:Map<String,Long>)
@Serializable data class AccountDeletionRequest(val password:String?=null,val confirmation:String)
@Serializable data class UpdateConversationRequest(val title:String?=null,val pinned:Boolean?=null,val archived:Boolean?=null,val learningMode:String?=null,val memoryEnabled:Boolean?=null,val projectMemoryEnabled:Boolean?=null,val expectedRevision:Long)
@Serializable data class EditMessageRequest(val text:String,val idempotencyKey:String)
@Serializable data class UpdateSourceRequest(val title:String?=null,val favorite:Boolean?=null,val pinned:Boolean?=null,val archived:Boolean?=null,val expectedRevision:Long)

@Serializable data class AiCancelRequest(val requestId:String)
@Serializable data class AiCancelResponse(val cancelled:Boolean)
@Serializable data class ActivityEventResponse(val eventId:String,val type:String,val occurredAt:String,val projectId:String?,val objectId:String?,val meaningful:Boolean)
@Serializable data class PersonalSnapshotResponse(val accountId:String,val displayName:String,val preferredLanguage:String,val timezone:String,val memoryMaturity:String,val activeProjects:Int,val completedAssessments:Int,val activeMistakes:Int,val dueFlashcards:Int,val recentActivity:List<ActivityEventResponse>,val schemaVersion:Int=1,val game:GameProfileSnapshotResponse?=null)
@Serializable data class ProjectInstructionPutRequest(val body:String,val structuredJson:String="{}")
@Serializable data class ProjectInstructionResponse(val id:String,val projectId:String,val body:String,val structuredJson:String,val version:Int,val active:Boolean,val updatedAt:String)

@Serializable data class UpdateGoalRequest(val title:String?=null,val description:String?=null,val priority:Int?=null,val targetDate:String?=null,val progress:Double?=null,val expectedRevision:Long)
@Serializable data class ProjectTemplateResponse(val id:String,val suggestedModules:List<String>,val starterGoals:List<String>,val instructionIdeas:List<String>)
@Serializable data class UpdateCardRequest(val front:String?=null,val back:String?=null,val explanation:String?=null,val favorite:Boolean?=null,val suspended:Boolean?=null,val expectedRevision:Long)
@Serializable data class DeckStatsResponse(val deckId:String,val total:Int,val due:Int,val suspended:Int,val reviewed:Int)
@Serializable data class MistakePracticeRequest(val idempotencyKey:String)
@Serializable data class MistakeFlashcardRequest(val deckId:String?=null,val deckTitle:String="Mistake Review",val idempotencyKey:String)
@Serializable data class SourceCollectionCreateRequest(val title:String,val parentId:String?=null)
@Serializable data class SourceCollectionResponse(val id:String,val parentId:String?,val title:String,val revision:Long)
@Serializable data class SourceAnnotationCreateRequest(val sourceVersion:Long=1,val chunkId:String?=null,val type:String,val body:String?=null,val locatorJson:String="{}")
@Serializable data class SourceAnnotationResponse(val id:String,val sourceId:String,val sourceVersion:Long,val chunkId:String?,val type:String,val body:String?,val locatorJson:String,val revision:Long)
@Serializable data class TranslationResponse(val translatedText:String,val sourceLanguage:String?,val targetLanguage:String,val provider:String,val live:Boolean,val createdAt:String)
@Serializable data class ChatArtifactRequest(val title:String?=null,val idempotencyKey:String)

@Serializable data class SyncMutationRequest(val mutationId:String,val entityType:String,val entityId:String,val operation:String,val expectedRevision:Long?=null,val idempotencyKey:String,val payload:Map<String,String> = emptyMap())
@Serializable data class SyncBatchRequest(val mutations:List<SyncMutationRequest>)
@Serializable data class SyncMutationResult(val mutationId:String,val status:String,val serverRevision:Long?=null,val code:String?=null,val retryable:Boolean=false)
@Serializable data class SyncBatchResponse(val results:List<SyncMutationResult>,val serverTime:String)
@Serializable data class RegenerateRequest(val idempotencyKey:String)
@Serializable data class RetryMessageRequest(val idempotencyKey:String)
@Serializable data class MessageAttachmentRequest(val type:String,val objectId:String,val state:String="READY",val metadata:Map<String,String> = emptyMap())
@Serializable data class MessageAttachmentResponse(val id:String,val conversationId:String,val messageId:String?,val type:String,val objectId:String?,val state:String,val metadata:Map<String,String>,val revision:Long)
@Serializable data class MessageCitationResponse(val index:Int,val citation:CitationResponse)
@Serializable data class ConversationBranchResponse(val rootMessageId:String,val activeTipMessageId:String,val messages:List<MessageResponse>)
@Serializable data class GeneratedArtifactRequest(val type:String,val title:String?=null,val projectId:String?=null,val conversationId:String?=null,val sourceIds:List<String> = emptyList(),val prompt:String,val idempotencyKey:String)
@Serializable data class GeneratedArtifactResponse(val id:String,val type:String,val state:String,val title:String,val projectId:String?,val conversationId:String?,val sourceIds:List<String>,val payloadJson:String,val revision:Long)
@Serializable data class ValidateArtifactRequest(val expectedRevision:Long)
@Serializable data class HybridSearchRequest(val query:String,val sourceIds:List<String> = emptyList(),val projectId:String?=null,val limit:Int=8)
@Serializable data class HybridSearchHitResponse(val citation:CitationResponse,val lexicalScore:Double,val semanticScore:Double,val fusedScore:Double)
@Serializable data class StorageHeadResponse(val provider:String,val key:String,val size:Long,val mimeType:String?,val etag:String?,val sha256:String?,val signedReadUrl:String?)
@Serializable data class AiContextDebugResponse(val projectId:String?,val instructionPresent:Boolean,val memoryCount:Int,val citationCount:Int,val learningMode:String,val toolIds:List<String>,val fingerprint:String)
@Serializable data class RouteManifestResponse(val version:String,val paths:List<String>)
@Serializable data class PracticeConfigRequest(val projectId:String?=null,val sourceIds:List<String> = emptyList(),val focusTopic:String?=null,val targetMistakeId:String?=null,val difficulty:Int=2,val targetItemCount:Int=8,val adaptive:Boolean=true,val hintPolicy:String="ON_REQUEST",val revealPolicy:String="AFTER_CHECK")
@Serializable data class PracticeItemResponse(val id:String,val sessionId:String,val position:Int,val prompt:String,val itemType:String,val state:String,val difficulty:Int,val topic:String?,val userAnswer:String?,val revision:Long)
@Serializable data class PracticeSessionDetailResponse(val session:PracticeResponse,val currentPosition:Int,val targetItemCount:Int,val difficulty:Int,val adaptive:Boolean,val hintPolicy:String,val revealPolicy:String,val items:List<PracticeItemResponse>,val summaryJson:String)
@Serializable data class PracticeSeedItemRequest(val prompt:String,val expectedAnswer:String,val explanation:String="",val itemType:String="SHORT_ANSWER",val topic:String?=null,val difficulty:Int=2)
@Serializable data class PracticeAttemptRequest(val answer:String,val idempotencyKey:String)
@Serializable data class PracticeAttemptResponse(val attemptId:String,val itemId:String,val attemptNumber:Int,val answer:String,val correct:Boolean?,val score:Double?)
@Serializable data class PracticeHintResponse(val itemId:String,val hintIndex:Int,val body:String)
@Serializable data class PracticeCheckResponse(val item:PracticeItemResponse,val correct:Boolean,val score:Double,val explanation:String,val nextItemId:String?,val mistakeId:String?)
@Serializable data class PracticeCompleteResponse(val session:PracticeResponse,val answered:Int,val correct:Int,val accuracy:Double,val summaryJson:String)
@Serializable data class ConversationLinkProjectRequest(val projectId:String?,val expectedRevision:Long)
