package com.veltrix.hom.vnext.server

import com.veltrix.hom.vnext.core.DomainError
import com.veltrix.hom.vnext.core.DomainException
import com.veltrix.hom.vnext.core.ErrorCategory
import java.sql.Connection
import java.util.UUID

class ChatIntelligenceRepository(private val db:Database) {
    fun attach(accountId:String,conversationId:String,messageId:String?,req:MessageAttachmentRequest):MessageAttachmentResponse=db.tx{c->
        requireConversation(c,accountId,conversationId);messageId?.let{requireMessage(c,accountId,conversationId,it)}
        val type=req.type.uppercase();if(type !in setOf("SOURCE","UPLOAD","IMAGE","NOTE","CAMERA"))throw validation("Unsupported attachment type")
        val state=req.state.uppercase();if(state !in setOf("UPLOADING","PROCESSING","READY","FAILED"))throw validation("Invalid attachment state")
        val objectId=req.objectId.takeIf{it.isNotBlank()};when(type){"SOURCE","UPLOAD","IMAGE","CAMERA"->objectId?.let{requireOwned(c,"source",accountId,it)};"NOTE"->objectId?.let{requireOwned(c,"note",accountId,it)}}
        val meta=mapJson(req.metadata)
        c.prepareStatement("INSERT INTO message_attachment(account_id,conversation_id,message_id,attachment_type,object_id,state,metadata) VALUES (?::uuid,?::uuid,?::uuid,?,?::uuid,?,?::jsonb) RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,conversationId);ps.setString(3,messageId);ps.setString(4,type);ps.setString(5,objectId);ps.setString(6,state);ps.setString(7,meta);ps.executeQuery().use{rs->rs.next();mapAttachment(rs)}}
    }
    fun attachments(accountId:String,conversationId:String,messageId:String?=null):List<MessageAttachmentResponse> =db.tx{c->requireConversation(c,accountId,conversationId);val sql="SELECT * FROM message_attachment WHERE account_id=?::uuid AND conversation_id=?::uuid"+(if(messageId!=null)" AND message_id=?::uuid" else "")+" ORDER BY created_at,id";c.prepareStatement(sql).use{ps->ps.setString(1,accountId);ps.setString(2,conversationId);if(messageId!=null)ps.setString(3,messageId);ps.executeQuery().use{rs->buildList{while(rs.next())add(mapAttachment(rs))}}}}
    fun requireReadyAttachments(accountId:String,conversationId:String,messageId:String?=null){val values=attachments(accountId,conversationId,messageId);val pending=values.filter{it.state !in setOf("READY","FAILED")};if(pending.isNotEmpty())throw DomainException(DomainError("SOURCE_NOT_READY",ErrorCategory.SOURCE_PROCESSING,"${pending.size} attachment(s) are still processing",true))}


    data class AttachmentContext(val sourceIds:List<String>, val noteContext:String)
    fun resolveAttachmentContext(accountId:String,conversationId:String,attachmentIds:List<String>):AttachmentContext = db.tx { c ->
        requireConversation(c,accountId,conversationId)
        if(attachmentIds.isEmpty()) return@tx AttachmentContext(emptyList(),"")
        val ids=attachmentIds.distinct().take(16)
        val found=mutableListOf<Triple<String,String,String?>>()
        c.prepareStatement("SELECT id::text,attachment_type,object_id::text,state FROM message_attachment WHERE account_id=?::uuid AND conversation_id=?::uuid AND id = ANY(?::uuid[])").use { ps ->
            ps.setString(1,accountId);ps.setArray(2,c.createArrayOf("uuid",ids.toTypedArray()));ps.executeQuery().use { rs -> while(rs.next()) {
                val id=rs.getString(1);val type=rs.getString(2);val objectId=rs.getString(3);val state=rs.getString(4)
                if(state!="READY") throw DomainException(DomainError("SOURCE_NOT_READY",ErrorCategory.SOURCE_PROCESSING,"Attachment $id is not ready",true))
                found += Triple(id,type,objectId)
            }}
        }
        if(found.map{it.first}.toSet()!=ids.toSet()) throw DomainException(DomainError("NOT_FOUND",ErrorCategory.NOT_FOUND,"Attachment not found"))
        val sourceIds=found.filter{it.second in setOf("SOURCE","UPLOAD","IMAGE","CAMERA")}.mapNotNull{it.third}.distinct()
        sourceIds.forEach{requireOwned(c,"source",accountId,it)}
        val notes=found.filter{it.second=="NOTE"}.mapNotNull{it.third}.map { noteId ->
            requireOwned(c,"note",accountId,noteId)
            c.prepareStatement("SELECT title,body FROM note WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,noteId);ps.setString(2,accountId);ps.executeQuery().use{rs->if(rs.next())"NOTE ${rs.getString(1).take(160)}:\n${rs.getString(2).take(2500)}" else ""}}
        }.filter{it.isNotBlank()}
        AttachmentContext(sourceIds,notes.joinToString("\n\n").take(8000))
    }

    fun persistCitations(accountId:String,messageId:String,citations:List<CitationResponse>){db.tx{c->requireOwnedMessage(c,accountId,messageId);c.prepareStatement("DELETE FROM assistant_message_citation WHERE account_id=?::uuid AND message_id=?::uuid").use{ps->ps.setString(1,accountId);ps.setString(2,messageId);ps.executeUpdate()};c.prepareStatement("INSERT INTO assistant_message_citation(account_id,message_id,citation_index,source_id,source_version,chunk_id,page,section,text_hash,retrieval_score) VALUES (?::uuid,?::uuid,?,?::uuid,?,?::uuid,?,?,?,?)").use{ps->citations.take(32).forEachIndexed{i,x->requireOwned(c,"source",accountId,x.sourceId);ps.setString(1,accountId);ps.setString(2,messageId);ps.setInt(3,i);ps.setString(4,x.sourceId);ps.setLong(5,x.sourceVersion);ps.setString(6,x.chunkId);if(x.page==null)ps.setNull(7,java.sql.Types.INTEGER)else ps.setInt(7,x.page);ps.setString(8,x.section);ps.setString(9,x.textHash);ps.setDouble(10,x.relevance);ps.addBatch()};ps.executeBatch()}}}
    fun citations(accountId:String,messageId:String):List<MessageCitationResponse> =db.tx{c->requireOwnedMessage(c,accountId,messageId);c.prepareStatement("SELECT amc.*,sc.chunk_text FROM assistant_message_citation amc JOIN source_chunk sc ON sc.id=amc.chunk_id AND sc.account_id=amc.account_id WHERE amc.account_id=?::uuid AND amc.message_id=?::uuid ORDER BY citation_index").use{ps->ps.setString(1,accountId);ps.setString(2,messageId);ps.executeQuery().use{rs->buildList{while(rs.next())add(MessageCitationResponse(rs.getInt("citation_index"),CitationResponse(rs.uuid("source_id"),rs.getLong("source_version"),rs.uuid("chunk_id"),rs.getObject("page") as? Int,rs.getString("section"),rs.getDouble("retrieval_score"),rs.getString("text_hash"),rs.getString("chunk_text").take(700))))}}}}

    fun createRegeneration(accountId:String,conversationId:String,userMessageId:String,idempotencyKey:String):MessageResponse=db.tx{c->requireConversation(c,accountId,conversationId);requireMessage(c,accountId,conversationId,userMessageId);val previous=c.prepareStatement("SELECT id::text,COALESCE(max(regeneration_index),0) OVER () idx FROM conversation_message WHERE account_id=?::uuid AND conversation_id=?::uuid AND parent_message_id=?::uuid AND role='ASSISTANT' ORDER BY regeneration_index DESC,created_at DESC LIMIT 1").use{ps->ps.setString(1,accountId);ps.setString(2,conversationId);ps.setString(3,userMessageId);ps.executeQuery().use{rs->if(rs.next())rs.getString(1) to rs.getInt(2) else null}};c.prepareStatement("INSERT INTO conversation_message(account_id,conversation_id,parent_message_id,role,state,content,idempotency_key,final_marker,variant_of_message_id,regeneration_index) VALUES (?::uuid,?::uuid,?::uuid,'ASSISTANT','STREAMING','',?,false,?::uuid,?) ON CONFLICT(account_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,conversationId);ps.setString(3,userMessageId);ps.setString(4,idempotencyKey);ps.setString(5,previous?.first);ps.setInt(6,(previous?.second?:0)+1);ps.executeQuery().use{rs->rs.next();mapMessage(rs)}}}
    fun retryUser(accountId:String,conversationId:String,messageId:String,idempotencyKey:String):MessageResponse=db.tx{c->requireConversation(c,accountId,conversationId);val old=c.prepareStatement("SELECT * FROM conversation_message WHERE id=?::uuid AND account_id=?::uuid AND conversation_id=?::uuid AND role='USER'").use{ps->ps.setString(1,messageId);ps.setString(2,accountId);ps.setString(3,conversationId);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("MESSAGE_NOT_FOUND",ErrorCategory.NOT_FOUND,"User message not found"));mapMessage(rs)}};if(old.state !in setOf("FAILED","CANCELLED"))throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Only failed/cancelled user messages can be retried"));c.prepareStatement("INSERT INTO conversation_message(account_id,conversation_id,parent_message_id,branch_key,role,state,content,idempotency_key,final_marker) VALUES (?::uuid,?::uuid,?::uuid,?,'USER','QUEUED',?,?,false) ON CONFLICT(account_id,idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,conversationId);ps.setString(3,old.parentMessageId);ps.setString(4,old.branchKey);ps.setString(5,old.content);ps.setString(6,idempotencyKey);ps.executeQuery().use{rs->rs.next();mapMessage(rs)}}}

    fun linkProject(accountId:String,conversationId:String,projectId:String?,expectedRevision:Long):ConversationResponse=db.tx{c->val conv=requireConversation(c,accountId,conversationId);if(conv.revision!=expectedRevision)throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Conversation revision conflict"));projectId?.let{requireOwned(c,"project",accountId,it)};val scope=if(projectId==null)"GLOBAL" else "PROJECT";c.prepareStatement("UPDATE conversation SET project_id=?::uuid,scope=?,updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND revision=? RETURNING *").use{ps->ps.setString(1,projectId);ps.setString(2,scope);ps.setString(3,conversationId);ps.setString(4,accountId);ps.setLong(5,expectedRevision);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Conversation revision conflict"));mapConversation(rs)}}}

    private fun requireConversation(c:Connection,a:String,id:String):ConversationResponse=c.prepareStatement("SELECT * FROM conversation WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CONVERSATION_NOT_FOUND",ErrorCategory.NOT_FOUND,"Conversation not found"));mapConversation(rs)}}
    private fun requireMessage(c:Connection,a:String,conv:String,id:String){c.prepareStatement("SELECT 1 FROM conversation_message WHERE id=?::uuid AND account_id=?::uuid AND conversation_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.setString(3,conv);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("MESSAGE_NOT_FOUND",ErrorCategory.NOT_FOUND,"Message not found"))}}}
    private fun requireOwnedMessage(c:Connection,a:String,id:String){c.prepareStatement("SELECT 1 FROM conversation_message WHERE id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("MESSAGE_NOT_FOUND",ErrorCategory.NOT_FOUND,"Message not found"))}}}
    private fun requireOwned(c:Connection,t:String,a:String,id:String){require(t in setOf("source","project","note"));val deleted=if(t in setOf("source","project","note"))" AND deleted_at IS NULL" else "";c.prepareStatement("SELECT 1 FROM $t WHERE id=?::uuid AND account_id=?::uuid$deleted").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("NOT_FOUND",ErrorCategory.NOT_FOUND,"Linked object not found"))}}}
    private fun mapAttachment(rs:java.sql.ResultSet):MessageAttachmentResponse=MessageAttachmentResponse(rs.uuid("id"),rs.uuid("conversation_id"),rs.uuidOrNull("message_id"),rs.getString("attachment_type"),rs.uuidOrNull("object_id"),rs.getString("state"),emptyMap(),rs.getLong("revision"))
    private fun mapMessage(rs:java.sql.ResultSet)=MessageResponse(rs.uuid("id"),rs.uuid("conversation_id"),rs.uuidOrNull("parent_message_id"),rs.getString("branch_key"),rs.getString("role"),rs.getString("state"),rs.getString("content"),rs.getBoolean("final_marker"),rs.getLong("revision"),rs.instant("created_at"),rs.instant("updated_at"))
    private fun mapConversation(rs:java.sql.ResultSet)=ConversationResponse(rs.uuid("id"),rs.uuidOrNull("project_id"),rs.getString("scope"),rs.getString("title"),rs.getString("learning_mode"),rs.getBoolean("memory_enabled"),rs.getBoolean("project_memory_enabled"),rs.getBoolean("pinned"),rs.getBoolean("archived"),rs.getLong("revision"),rs.instant("updated_at"))
}
