package com.veltrix.hom.vnext.server

import com.veltrix.hom.vnext.core.*
import java.sql.Connection
import java.sql.ResultSet
import java.time.OffsetDateTime
import java.time.Instant

class AssessmentRepository(private val db: Database) {
    fun create(accountId:String, req:CreateAssessmentRequest):AssessmentResponse = db.tx { c ->
        val kind=req.kind.uppercase(); if(kind !in setOf("TEST","QUIZ")) throw validation("kind must be TEST or QUIZ")
        val title=req.title.trim(); if(title.isEmpty()||title.length>240) throw validation("Invalid assessment title")
        if(req.questions.isEmpty()||req.questions.size>300) throw validation("Assessment requires 1..300 questions")
        req.projectId?.let{requireProject(c,accountId,it)};validateQuestions(req.questions)
        val id=c.prepareStatement("INSERT INTO assessment(account_id,project_id,kind,title,state,created_by) VALUES (?::uuid,?::uuid,?,?,'READY','USER') RETURNING id,revision").use{ps->ps.setString(1,accountId);ps.setString(2,req.projectId);ps.setString(3,kind);ps.setString(4,title);ps.executeQuery().use{rs->rs.next();rs.uuid("id") to rs.getLong("revision")}}
        c.prepareStatement("INSERT INTO assessment_question(account_id,assessment_id,position,question_type,prompt,options,expected_answer,validator,evidence) VALUES (?::uuid,?::uuid,?,?,?,?::jsonb,?::jsonb,?::jsonb,?::jsonb)").use{ps->req.questions.forEachIndexed{index,q->ps.setString(1,accountId);ps.setString(2,id.first);ps.setInt(3,index);ps.setString(4,q.type.uppercase());ps.setString(5,q.prompt.trim());ps.setString(6,jsonArray(q.options));ps.setString(7,jsonArray(q.expectedAnswers));ps.setString(8,if(q.numericTolerance==null)"{}" else "{\"numericTolerance\":${q.numericTolerance}}" );ps.setString(9,citationJson(q.evidence));ps.addBatch()};ps.executeBatch()}
        AssessmentResponse(id.first,kind,title,req.projectId,"READY",req.questions.size,id.second)
    }

    /** Safe read model exposes question IDs/options needed to answer, never answer keys. */
    fun get(accountId:String,id:String):AssessmentDetailResponse=db.tx{c->AssessmentDetailResponse(ownedAssessment(c,accountId,id),publicQuestions(c,accountId,id))}

    fun startAttempt(accountId:String,assessmentId:String):AttemptResponse=db.tx{c->val a=ownedAssessment(c,accountId,assessmentId);c.prepareStatement("INSERT INTO assessment_attempt(account_id,assessment_id,project_id,state,started_at,last_active_at) VALUES (?::uuid,?::uuid,?::uuid,'IN_PROGRESS',now(),now()) RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,assessmentId);ps.setString(3,a.projectId);ps.executeQuery().use{rs->rs.next();mapAttempt(rs)}}}

    fun saveAnswer(accountId:String,attemptId:String,req:SaveAnswerRequest):AttemptResponse=db.tx{c->
        val attempt=ownedAttempt(c,accountId,attemptId);if(attempt.state!="IN_PROGRESS")throw DomainException(DomainError("ATTEMPT_ALREADY_SUBMITTED",ErrorCategory.CONFLICT,"Attempt is not editable"));requireQuestion(c,accountId,attempt.assessmentId,req.questionId)
        c.prepareStatement("INSERT INTO assessment_answer(attempt_id,question_id,account_id,answer) VALUES (?::uuid,?::uuid,?::uuid,?::jsonb) ON CONFLICT(attempt_id,question_id) DO UPDATE SET answer=excluded.answer,updated_at=now(),answered_at=now()").use{ps->ps.setString(1,attemptId);ps.setString(2,req.questionId);ps.setString(3,accountId);ps.setString(4,jsonArray(req.answers));ps.executeUpdate()}
        c.prepareStatement("UPDATE assessment_attempt SET last_active_at=now(),updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid RETURNING *").use{ps->ps.setString(1,attemptId);ps.setString(2,accountId);ps.executeQuery().use{rs->rs.next();mapAttempt(rs)}}
    }

    fun submit(accountId:String,attemptId:String):SubmitAttemptResponse=db.tx{c->
        val attempt=ownedAttempt(c,accountId,attemptId);if(attempt.state!="IN_PROGRESS")throw DomainException(DomainError("ATTEMPT_ALREADY_SUBMITTED",ErrorCategory.CONFLICT,"Attempt already submitted"))
        val questions=loadQuestions(c,accountId,attempt.assessmentId);val answers=loadAnswers(c,accountId,attemptId)
        val result=AssessmentEngine.score(Assessment(attempt.assessmentId,accountId,attempt.projectId,"ASSESSMENT","",questions),answers)
        c.prepareStatement("UPDATE assessment_attempt SET state='GRADED',submitted_at=now(),last_active_at=now(),score=?,result_summary=?::jsonb,updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND revision=? RETURNING *").use{ps->ps.setDouble(1,result.score);ps.setString(2,"{\"accuracy\":${result.accuracy}}");ps.setString(3,attemptId);ps.setString(4,accountId);ps.setLong(5,attempt.revision);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Attempt revision conflict"))}}
        val mistakes=mutableListOf<String>();result.results.filterNot{it.correct}.forEach{r->val q=questions.first{it.id==r.questionId};val user=answers[q.id]?.answers?.joinToString(" | ").orEmpty();val expected=q.expectedAnswers.joinToString(" | ");mistakes+=upsertMistake(c,accountId,attempt.projectId,questionSourceId(c,accountId,q.id),"assessment",q.prompt,user,expected)}
        val eventType=if(ownedAssessment(c,accountId,attempt.assessmentId).kind=="QUIZ")"QUIZ_COMPLETED" else "TEST_COMPLETED";insertActivity(c,accountId,eventType,attempt.projectId,attemptId,"assessment-submit:$attemptId",true)
        c.prepareStatement("INSERT INTO learning_signal(account_id,project_id,topic,kind,signal_value,confidence,evidence_ids) VALUES (?::uuid,?::uuid,'assessment','ASSESSMENT_ACCURACY',?,1.0,?::jsonb)").use{ps->ps.setString(1,accountId);ps.setString(2,attempt.projectId);ps.setDouble(3,result.accuracy);ps.setString(4,jsonArray(listOf(attemptId)));ps.executeUpdate()}
        val finalAttempt=ownedAttempt(c,accountId,attemptId);SubmitAttemptResponse(finalAttempt,result.score,result.accuracy,result.results.filterNot{it.correct}.map{it.questionId},mistakes)
    }

    private fun publicQuestions(c:Connection,a:String,assessment:String):List<AssessmentQuestionPublicResponse> =c.prepareStatement("SELECT id,position,prompt,question_type,options FROM assessment_question WHERE account_id=?::uuid AND assessment_id=?::uuid ORDER BY position").use{ps->ps.setString(1,a);ps.setString(2,assessment);ps.executeQuery().use{rs->buildList{while(rs.next())add(AssessmentQuestionPublicResponse(rs.uuid("id"),rs.getInt("position"),rs.getString("prompt"),rs.getString("question_type"),parseJsonStringArray(rs.getString("options"))))}}}
    private fun questionSourceId(c:Connection,a:String,q:String):String?=c.prepareStatement("SELECT evidence->0->>'sourceId' source_id FROM assessment_question WHERE id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,q);ps.setString(2,a);ps.executeQuery().use{rs->if(rs.next())rs.getString("source_id") else null}}
    private fun validateQuestions(qs:List<QuestionRequest>){qs.forEach{q->if(q.prompt.trim().isEmpty()||q.prompt.length>20_000)throw validation("Invalid question prompt");if(q.expectedAnswers.isEmpty())throw validation("Question requires expected answer");if(q.type.uppercase() !in setOf("SINGLE_CHOICE","MULTIPLE_CHOICE","TRUE_FALSE","SHORT_ANSWER","NUMERIC","FILL_BLANK","ORDERING","MATCHING"))throw validation("Unsupported question type: ${q.type}");q.numericTolerance?.let{if(it<0||!it.isFinite())throw validation("Invalid numeric tolerance")}}}
    private fun ownedAssessment(c:Connection,a:String,id:String):AssessmentResponse=c.prepareStatement("SELECT x.*,(SELECT count(*) FROM assessment_question q WHERE q.assessment_id=x.id) question_count FROM assessment x WHERE x.id=?::uuid AND x.account_id=?::uuid AND x.deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("ASSESSMENT_NOT_FOUND",ErrorCategory.NOT_FOUND,"Assessment not found"));AssessmentResponse(rs.uuid("id"),rs.getString("kind"),rs.getString("title"),rs.uuidOrNull("project_id"),rs.getString("state"),rs.getInt("question_count"),rs.getLong("revision"))}}
    private fun ownedAttempt(c:Connection,a:String,id:String):AttemptResponse=c.prepareStatement("SELECT * FROM assessment_attempt WHERE id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("ATTEMPT_NOT_FOUND",ErrorCategory.NOT_FOUND,"Attempt not found"));mapAttempt(rs)}}
    private fun requireQuestion(c:Connection,a:String,assessment:String,q:String){c.prepareStatement("SELECT 1 FROM assessment_question WHERE id=?::uuid AND account_id=?::uuid AND assessment_id=?::uuid").use{ps->ps.setString(1,q);ps.setString(2,a);ps.setString(3,assessment);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("QUESTION_NOT_FOUND",ErrorCategory.NOT_FOUND,"Question not found"))}}}
    private fun loadQuestions(c:Connection,a:String,assessment:String):List<Question> =c.prepareStatement("SELECT * FROM assessment_question WHERE account_id=?::uuid AND assessment_id=?::uuid ORDER BY position").use{ps->ps.setString(1,a);ps.setString(2,assessment);ps.executeQuery().use{rs->buildList{while(rs.next()){val validator=rs.getString("validator");val tolerance=Regex("\\\"numericTolerance\\\"\\s*:\\s*([0-9.eE+-]+)").find(validator)?.groupValues?.get(1)?.toDoubleOrNull();add(Question(rs.uuid("id"),rs.getString("prompt"),rs.getString("question_type"),parseJsonStringArray(rs.getString("options")),parseJsonStringArray(rs.getString("expected_answer")),tolerance))}}}}
    private fun loadAnswers(c:Connection,a:String,attempt:String):Map<String,AttemptAnswer> =c.prepareStatement("SELECT question_id,answer,answered_at FROM assessment_answer WHERE account_id=?::uuid AND attempt_id=?::uuid").use{ps->ps.setString(1,a);ps.setString(2,attempt);ps.executeQuery().use{rs->buildMap{while(rs.next()){val q=rs.uuid("question_id");put(q,AttemptAnswer(q,parseJsonStringArray(rs.getString("answer")),rs.getObject("answered_at",OffsetDateTime::class.java).toInstant()))}}}}
    private fun mapAttempt(rs:ResultSet)=AttemptResponse(rs.uuid("id"),rs.uuid("assessment_id"),rs.uuidOrNull("project_id"),rs.getString("state"),rs.getObject("score")?.let{(it as Number).toDouble()},rs.getLong("revision"))
    private fun requireProject(c:Connection,a:String,id:String){c.prepareStatement("SELECT 1 FROM project WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("PROJECT_NOT_FOUND",ErrorCategory.NOT_FOUND,"Project not found"))}}}
}

internal fun upsertMistake(c:Connection,accountId:String,projectId:String?,sourceId:String?,topic:String,prompt:String,user:String,expected:String):String{val existing=c.prepareStatement("SELECT id FROM mistake WHERE account_id=?::uuid AND project_id IS NOT DISTINCT FROM ?::uuid AND source_id IS NOT DISTINCT FROM ?::uuid AND topic=? AND prompt=? AND status<>'ARCHIVED' AND deleted_at IS NULL LIMIT 1").use{ps->ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,sourceId);ps.setString(4,topic);ps.setString(5,prompt);ps.executeQuery().use{rs->if(rs.next())rs.uuid("id")else null}};if(existing!=null){c.prepareStatement("UPDATE mistake SET user_answer=?,expected_answer=?,occurrence_count=occurrence_count+1,last_seen_at=now(),status='ACTIVE',revision=revision+1 WHERE id=?::uuid").use{ps->ps.setString(1,user);ps.setString(2,expected);ps.setString(3,existing);ps.executeUpdate()};return existing};return c.prepareStatement("INSERT INTO mistake(account_id,project_id,source_id,topic,prompt,user_answer,expected_answer) VALUES (?::uuid,?::uuid,?::uuid,?,?,?,?) RETURNING id").use{ps->ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,sourceId);ps.setString(4,topic);ps.setString(5,prompt);ps.setString(6,user);ps.setString(7,expected);ps.executeQuery().use{rs->rs.next();rs.uuid("id")}}}
internal fun insertActivity(c:Connection,accountId:String,type:String,projectId:String?,objectId:String?,key:String,meaningful:Boolean){c.prepareStatement("INSERT INTO activity_event(account_id,event_type,project_id,object_id,idempotency_key,meaningful) VALUES (?::uuid,?,?::uuid,?,?,?) ON CONFLICT(account_id,idempotency_key) DO NOTHING").use{ps->ps.setString(1,accountId);ps.setString(2,type);ps.setString(3,projectId);ps.setString(4,objectId);ps.setString(5,key);ps.setBoolean(6,meaningful);ps.executeUpdate()}}
internal fun jsonArray(values:List<String>):String=values.joinToString(prefix="[",postfix="]"){"\""+it.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n")+"\""}
internal fun parseJsonStringArray(json:String?):List<String>{if(json.isNullOrBlank())return emptyList();return Regex("\\\"((?:\\\\.|[^\\\"])*)\\\"").findAll(json).map{it.groupValues[1].replace("\\n","\n").replace("\\\"","\"").replace("\\\\","\\")}.toList()}
internal fun citationJson(values:List<CitationResponse>):String="["+values.joinToString(","){"{\"sourceId\":\"${it.sourceId}\",\"sourceVersion\":${it.sourceVersion},\"chunkId\":\"${it.chunkId}\",\"textHash\":\"${it.textHash}\"}"}+"]"
internal fun scheduleJson(s:FlashcardScheduleState)="{\"intervalDays\":${s.intervalDays},\"ease\":${s.ease},\"repetitions\":${s.repetitions},\"lapses\":${s.lapses},\"dueAt\":\"${s.dueAt}\"}"
