package com.veltrix.hom.vnext.server

import com.veltrix.hom.vnext.core.HomeInsightEngine
import com.veltrix.hom.vnext.core.HomePriorityCandidate
import com.veltrix.hom.vnext.core.HomePriorityEngine
import com.veltrix.hom.vnext.core.LevelCurveV1
import com.veltrix.hom.vnext.core.WorldContinuityEngine
import java.sql.Connection
import java.time.Instant
import java.time.OffsetDateTime

internal class Part3SnapshotRepository(
    private val db:Database,private val projects:ProjectRepository,private val chats:ChatRepository,private val memory:MemoryRepository,
    private val projectInstructions:ProjectInstructionRepository,private val student:Part3StudentRepository,
){
    fun home(accountId:String):HomeSnapshotV3Response{
        val maturity=memory.maturity(accountId).state
        return db.tx{c->
            val identity=c.prepareStatement("""SELECT p.display_name,p.username,COALESCE(e.avatar_id,NULLIF(p.default_avatar_id,'default'),'avatar-noob-default'),COALESCE(g.level,1),COALESCE(g.effective_level,1),COALESCE(g.lifetime_xp,0),COALESCE(g.qualified_active_days,0),COALESCE(cp.balance,0),COALESCE(cs.current_consistency,0),COALESCE(cs.longest_consistency,0),COALESCE(g.revision,0) FROM user_profile p LEFT JOIN progression_profile g ON g.account_id=p.account_id LEFT JOIN coin_account_projection cp ON cp.account_id=p.account_id LEFT JOIN consistency_state cs ON cs.account_id=p.account_id LEFT JOIN equipped_avatar e ON e.account_id=p.account_id WHERE p.account_id=?::uuid""").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->if(!rs.next())throw notFound("Profile not found");arrayOf(rs.getString(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getInt(5),rs.getLong(6),rs.getInt(7),rs.getLong(8),rs.getInt(9),rs.getInt(10),rs.getLong(11))}}
            val xpLevel=identity[3] as Int;val effective=identity[4] as Int;val xp=identity[5] as Long
            val start=LevelCurveV1.xpRequiredForLevel(xpLevel);val next=if(xpLevel>=50)start else LevelCurveV1.xpRequiredForLevel(xpLevel+1);val current=(xp-start).coerceAtLeast(0);val remaining=(next-xp).coerceAtLeast(0)
            val recent=homeProjects(c,accountId,6);val focus=recent.firstOrNull();val score=c.prepareStatement("SELECT score FROM assessment_attempt WHERE account_id=?::uuid AND state='GRADED' ORDER BY updated_at DESC LIMIT 1").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->if(rs.next())rs.getObject(1)?.let{rs.getDouble(1)}else null}}
            val topics=c.prepareStatement("SELECT topic FROM mistake WHERE account_id=?::uuid AND status IN('ACTIVE','IMPROVING','RECURRED') AND deleted_at IS NULL AND topic IS NOT NULL GROUP BY topic ORDER BY count(*) DESC,max(last_seen_at) DESC LIMIT 5").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->buildList{while(rs.next())add(rs.getString(1))}}};val sources=homeSources(c,accountId,6)
            val map=c.prepareStatement("SELECT pm.state,mup.unit_id,pm.id FROM personal_map pm LEFT JOIN map_unit_progress mup ON mup.personal_map_id=pm.id AND mup.account_id=pm.account_id AND mup.state IN('AVAILABLE','IN_PROGRESS') WHERE pm.account_id=?::uuid ORDER BY pm.updated_at DESC,mup.unit_id LIMIT 1").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->if(rs.next())Triple(rs.getString(1),rs.getString(2),rs.getObject(3).toString())else Triple("LOCKED",null,null)}}
            val season=c.prepareStatement("SELECT season_id FROM season_definition WHERE state='ACTIVE' AND start_at<=now() AND end_at>now() ORDER BY start_at DESC LIMIT 1").use{ps->ps.executeQuery().use{rs->if(rs.next())rs.getString(1)else null}}
            val indicators=count(c,"SELECT count(*) FROM achievement_progress WHERE account_id=?::uuid AND state IN('UNLOCKED','CLAIMED')",accountId);val unread=count(c,"SELECT count(*) FROM notification_intent WHERE account_id=?::uuid AND status='PENDING' AND(scheduled_for IS NULL OR scheduled_for<=now())",accountId)
            val candidates=buildList{if(focus!=null)add(HomePriorityCandidate("PROJECT_FOCUS",80,focus.priority));if(topics.isNotEmpty())add(HomePriorityCandidate("WEAK_REVIEW",70,dueSoon=true));if(map.first in setOf("ACTIVE","ELIGIBLE"))add(HomePriorityCandidate("PERSONAL_MAP",65));if(sources.isNotEmpty())add(HomePriorityCandidate("RECENT_SOURCE",45))};val priority=HomePriorityEngine.rank(candidates);val insights=HomeInsightEngine.deterministic(remaining,activeGoals(c,accountId),topics.size,map.first)
            val world=WorldContinuityEngine.ids(accountId,focus?.id,map.third,season);val eligible=effective>=5&&maturity in setOf("SUFFICIENT","STRONG")
            HomeSnapshotV3Response(accountId,identity[0] as String,identity[1] as String?,identity[2] as String,effective,xpLevel,xp,current,next,remaining,identity[7] as Long,identity[6] as Int,identity[8] as Int,identity[9] as Int,focus,recent,score,topics,sources,mapOf("PROJECT" to(focus!=null),"REVIEW" to topics.isNotEmpty(),"MAP" to eligible,"FLASHCARDS" to hasDue(c,accountId)),maturity,eligible,map.first,map.second,season,indicators,unread,"SERVER_AUTHORITATIVE",HomePriorityResponse(priority.orderedKeys,priority.scores),insights.map{HomeInsightResponse(it.code,it.textKey,it.numericValue,it.evidenceIds)},WorldContinuityResponse(world.avatarEntityId,world.accountProgressEntityId,world.coinBalanceEntityId,world.projectEntityId,world.mapEntityId,world.seasonEntityId),identity[10] as Long,Instant.now().toString())
        }
    }

    fun personal(accountId:String):PersonalSnapshotV3Response{
        val maturity=memory.maturity(accountId).state
        return db.tx{c->
            val p=c.prepareStatement("""SELECT p.display_name,p.username,p.preferred_language,p.timezone,COALESCE(e.avatar_id,NULLIF(p.default_avatar_id,'default'),'avatar-noob-default'),COALESCE(g.effective_level,1),COALESCE(g.level,1),COALESCE(g.lifetime_xp,0),COALESCE(cp.balance,0),COALESCE(g.qualified_active_days,0),COALESCE(cs.current_consistency,0),COALESCE(cs.longest_consistency,0),COALESCE(g.revision,0) FROM user_profile p LEFT JOIN equipped_avatar e ON e.account_id=p.account_id LEFT JOIN progression_profile g ON g.account_id=p.account_id LEFT JOIN coin_account_projection cp ON cp.account_id=p.account_id LEFT JOIN consistency_state cs ON cs.account_id=p.account_id WHERE p.account_id=?::uuid""").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->if(!rs.next())throw notFound("Profile not found");arrayOf(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getInt(6),rs.getInt(7),rs.getLong(8),rs.getLong(9),rs.getInt(10),rs.getInt(11),rs.getInt(12),rs.getLong(13))}}
            fun cnt(sql:String)=count(c,sql,accountId);fun values(type:String)=c.prepareStatement("SELECT structured_value::text FROM student_signal WHERE account_id=?::uuid AND signal_type=? AND status IN('ACTIVE','CONFIRMED') AND deleted_at IS NULL ORDER BY confidence DESC,updated_at DESC LIMIT 5").use{ps->ps.setString(1,accountId);ps.setString(2,type);ps.executeQuery().use{rs->buildList{while(rs.next())add(rs.getString(1))}}}
            val season=c.prepareStatement("SELECT season_id FROM season_definition WHERE state='ACTIVE' AND start_at<=now() AND end_at>now() ORDER BY start_at DESC LIMIT 1").use{ps->ps.executeQuery().use{rs->if(rs.next())rs.getString(1)else null}};val mapState=c.prepareStatement("SELECT state FROM personal_map WHERE account_id=?::uuid ORDER BY updated_at DESC LIMIT 1").use{ps->ps.setString(1,accountId);ps.executeQuery().use{rs->if(rs.next())rs.getString(1)else "LOCKED"}}
            val world=WorldContinuityEngine.ids(accountId,null,null,season)
            PersonalSnapshotV3Response(accountId,p[0] as String,p[1] as String?,p[2] as String,p[3] as String,p[4] as String,p[5] as Int,p[6] as Int,p[7] as Long,p[8] as Long,p[9] as Int,StudentModelSummaryResponse(maturity,cnt("SELECT count(*) FROM student_signal WHERE account_id=?::uuid AND status='ACTIVE' AND deleted_at IS NULL"),cnt("SELECT count(*) FROM student_signal WHERE account_id=?::uuid AND status='CONFIRMED' AND deleted_at IS NULL"),cnt("SELECT count(*) FROM student_signal WHERE account_id=?::uuid AND project_id IS NOT NULL AND deleted_at IS NULL"),cnt("SELECT count(*) FROM student_signal WHERE account_id=?::uuid AND signal_type='PERFORMANCE' AND deleted_at IS NULL"),cnt("SELECT count(*) FROM student_signal WHERE account_id=?::uuid AND signal_type='MISTAKE' AND deleted_at IS NULL")),values("PERFORMANCE"),values("MISTAKE"),values("INTEREST"),values("GOAL"),cnt("SELECT count(*) FROM project WHERE account_id=?::uuid AND status='ACTIVE' AND deleted_at IS NULL"),cnt("SELECT count(*) FROM assessment_attempt WHERE account_id=?::uuid AND state='GRADED'"),cnt("SELECT count(*) FROM flashcard_schedule WHERE account_id=?::uuid AND due_at<=now()"),cnt("SELECT count(*) FROM mistake WHERE account_id=?::uuid AND status IN('ACTIVE','IMPROVING','RECURRED') AND deleted_at IS NULL"),mapState,season,cnt("SELECT count(*) FROM achievement_progress WHERE account_id=?::uuid AND state IN('UNLOCKED','CLAIMED')"),cnt("SELECT count(*) FROM inventory_ownership WHERE account_id=?::uuid"),p[10] as Int,p[11] as Int,activity(c,accountId,10),WorldContinuityResponse(world.avatarEntityId,world.accountProgressEntityId,world.coinBalanceEntityId,world.projectEntityId,world.mapEntityId,world.seasonEntityId),p[12] as Long,Instant.now().toString())
        }
    }

    fun workspace(accountId:String,projectId:String):ProjectWorkspaceV3Response{
        val project=projects.get(accountId,projectId);val goals=projects.listGoals(accountId,projectId);val recent=chats.list(accountId,projectId,8,0);val instruction=projectInstructions.active(accountId,projectId);val recs=student.recommendations(accountId,projectId,5);val context=student.getContext(accountId)?.takeIf{it.projectId==projectId}
        val data=db.tx{c->fun countProject(table:String,deleted:Boolean=true):Int{val suffix=if(deleted)" AND deleted_at IS NULL" else "";return c.prepareStatement("SELECT count(*) FROM $table WHERE account_id=?::uuid AND project_id=?::uuid$suffix").use{ps->ps.setString(1,accountId);ps.setString(2,projectId);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}}};arrayOf(c.prepareStatement("SELECT count(*) FROM source_project_link WHERE account_id=?::uuid AND project_id=?::uuid").use{ps->ps.setString(1,accountId);ps.setString(2,projectId);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}},countProject("note"),countProject("assessment"),countProject("flashcard"),countProject("mistake"),countProject("practice_session",false),countProject("student_signal"),c.prepareStatement("SELECT count(*) FROM activity_event WHERE account_id=?::uuid AND project_id=?::uuid AND meaningful=true").use{ps->ps.setString(1,accountId);ps.setString(2,projectId);ps.executeQuery().use{rs->rs.next();rs.getLong(1)}})}
        val world=WorldContinuityEngine.ids(accountId,projectId);return ProjectWorkspaceV3Response(project,goals,recent,data[0] as Int,data[1] as Int,data[2] as Int,data[3] as Int,data[4] as Int,data[5] as Int,data[6] as Int,data[7] as Long,instruction,recs,context,WorldContinuityResponse(world.avatarEntityId,world.accountProgressEntityId,world.coinBalanceEntityId,world.projectEntityId,world.mapEntityId,world.seasonEntityId),project.revision,Instant.now().toString())
    }

    private fun homeProjects(c:Connection,a:String,limit:Int)=c.prepareStatement("""SELECT p.id,p.title,p.purpose,p.priority,p.revision,(SELECT count(*) FROM goal g WHERE g.account_id=p.account_id AND g.project_id=p.id AND g.status IN('ACTIVE','PAUSED') AND g.deleted_at IS NULL),(SELECT count(*) FROM activity_event e WHERE e.account_id=p.account_id AND e.project_id=p.id AND e.meaningful=true) FROM project p WHERE p.account_id=?::uuid AND p.status='ACTIVE' AND p.deleted_at IS NULL ORDER BY p.priority DESC,p.last_active_at DESC LIMIT ?""").use{ps->ps.setString(1,a);ps.setInt(2,limit);ps.executeQuery().use{rs->buildList{while(rs.next())add(HomeProjectFocusResponse(rs.getObject(1).toString(),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getInt(6),rs.getLong(7),rs.getLong(5)))}}}
    private fun homeSources(c:Connection,a:String,limit:Int)=c.prepareStatement("SELECT id,title,state,pinned,favorite,revision FROM source WHERE account_id=?::uuid AND deleted_at IS NULL ORDER BY pinned DESC,favorite DESC,updated_at DESC LIMIT ?").use{ps->ps.setString(1,a);ps.setInt(2,limit);ps.executeQuery().use{rs->buildList{while(rs.next())add(HomeSourceBriefResponse(rs.getObject(1).toString(),rs.getString(2),rs.getString(3),rs.getBoolean(4),rs.getBoolean(5),rs.getLong(6)))}}}
    private fun activity(c:Connection,a:String,limit:Int)=c.prepareStatement("SELECT event_id,event_type,occurred_at,project_id,object_id,meaningful FROM activity_event WHERE account_id=?::uuid ORDER BY occurred_at DESC,event_id DESC LIMIT ?").use{ps->ps.setString(1,a);ps.setInt(2,limit);ps.executeQuery().use{rs->buildList{while(rs.next())add(ActivityEventResponse(rs.getObject(1).toString(),rs.getString(2),rs.getObject(3,OffsetDateTime::class.java).toInstant().toString(),rs.getObject(4)?.toString(),rs.getString(5),rs.getBoolean(6)))}}}
    private fun activeGoals(c:Connection,a:String)=count(c,"SELECT count(*) FROM goal WHERE account_id=?::uuid AND status IN('ACTIVE','PAUSED') AND deleted_at IS NULL",a)
    private fun hasDue(c:Connection,a:String)=c.prepareStatement("SELECT EXISTS(SELECT 1 FROM flashcard_schedule WHERE account_id=?::uuid AND due_at<=now())").use{ps->ps.setString(1,a);ps.executeQuery().use{rs->rs.next();rs.getBoolean(1)}}
    private fun count(c:Connection,sql:String,a:String)=c.prepareStatement(sql).use{ps->ps.setString(1,a);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}}
    private fun notFound(m:String)=com.veltrix.hom.vnext.core.DomainException(com.veltrix.hom.vnext.core.DomainError("NOT_FOUND",com.veltrix.hom.vnext.core.ErrorCategory.NOT_FOUND,m))
}
