package com.veltrix.hom.vnext.server

import com.veltrix.hom.vnext.core.DomainError
import com.veltrix.hom.vnext.core.DomainException
import com.veltrix.hom.vnext.core.ErrorCategory
import java.sql.Connection
import java.time.OffsetDateTime
import java.time.ZoneOffset

/** Part 3 depth repository: versioned modes, Goal graph, retest history and complete user-data export. */
class Part3CompletionRepository(private val db:Database) {
    fun learningModes():List<LearningModeDefinitionResponse> = db.tx { c ->
        c.prepareStatement("SELECT mode_id,version,answer_depth,guiding_questions,reveal_answers_immediately,citation_preference,correction_style,prompt_policy::text,tool_policy::text,assessment_policy::text FROM learning_mode_definition WHERE state='ACTIVE' ORDER BY mode_id").use { ps ->
            ps.executeQuery().use { rs -> buildList { while(rs.next()) add(LearningModeDefinitionResponse(rs.getString(1),rs.getInt(2),rs.getString(3),rs.getBoolean(4),rs.getBoolean(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10))) } }
        }
    }
    fun goalDependencies(accountId:String,projectId:String,goalId:String):List<GoalDependencyResponse> = db.tx { c ->
        goal(c,accountId,projectId,goalId); c.prepareStatement("SELECT goal_id,depends_on_goal_id,created_at FROM goal_dependency WHERE account_id=?::uuid AND project_id=?::uuid AND goal_id=?::uuid ORDER BY created_at,depends_on_goal_id").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,goalId);ps.executeQuery().use { rs -> buildList { while(rs.next()) add(GoalDependencyResponse(rs.getString(1),rs.getString(2),rs.getObject(3,OffsetDateTime::class.java).toInstant().toString())) } } }
    }
    fun addGoalDependency(accountId:String,projectId:String,goalId:String,req:GoalDependencyRequest):GoalDependencyResponse = db.tx { c ->
        goal(c,accountId,projectId,goalId);goal(c,accountId,projectId,req.dependsOnGoalId);if(goalId==req.dependsOnGoalId) throw validation("Goal cannot depend on itself");if(pathExists(c,accountId,req.dependsOnGoalId,goalId)) throw DomainException(DomainError("GOAL_DEPENDENCY_CYCLE",ErrorCategory.CONFLICT,"Goal dependency would create a cycle"));c.prepareStatement("INSERT INTO goal_dependency(account_id,project_id,goal_id,depends_on_goal_id) VALUES (?::uuid,?::uuid,?::uuid,?::uuid) ON CONFLICT(account_id,goal_id,depends_on_goal_id) DO UPDATE SET project_id=EXCLUDED.project_id RETURNING goal_id,depends_on_goal_id,created_at").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,goalId);ps.setString(4,req.dependsOnGoalId);ps.executeQuery().use { rs -> rs.next();GoalDependencyResponse(rs.getString(1),rs.getString(2),rs.getObject(3,OffsetDateTime::class.java).toInstant().toString()) } }
    }
    fun removeGoalDependency(accountId:String,projectId:String,goalId:String,dependsOnGoalId:String) { db.tx { c -> goal(c,accountId,projectId,goalId);c.prepareStatement("DELETE FROM goal_dependency WHERE account_id=?::uuid AND project_id=?::uuid AND goal_id=?::uuid AND depends_on_goal_id=?::uuid").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,goalId);ps.setString(4,dependsOnGoalId);ps.executeUpdate() } } }
    fun goalLinks(accountId:String,projectId:String,goalId:String):List<GoalLinkResponse> = db.tx { c -> goal(c,accountId,projectId,goalId);c.prepareStatement("SELECT id,goal_id,object_type,object_id,created_at FROM goal_link WHERE account_id=?::uuid AND project_id=?::uuid AND goal_id=?::uuid ORDER BY created_at,id").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,goalId);ps.executeQuery().use { rs -> buildList { while(rs.next()) add(GoalLinkResponse(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getObject(5,OffsetDateTime::class.java).toInstant().toString())) } } } }
    fun addGoalLink(accountId:String,projectId:String,goalId:String,req:GoalLinkRequest):GoalLinkResponse = db.tx { c -> goal(c,accountId,projectId,goalId);val type=req.objectType.uppercase();validateGoalLinkObject(c,accountId,projectId,type,req.objectId);c.prepareStatement("INSERT INTO goal_link(account_id,project_id,goal_id,object_type,object_id) VALUES (?::uuid,?::uuid,?::uuid,?,?::uuid) ON CONFLICT(account_id,goal_id,object_type,object_id) DO UPDATE SET project_id=EXCLUDED.project_id RETURNING id,goal_id,object_type,object_id,created_at").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,goalId);ps.setString(4,type);ps.setString(5,req.objectId);ps.executeQuery().use { rs -> rs.next();GoalLinkResponse(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getObject(5,OffsetDateTime::class.java).toInstant().toString()) } } }
    fun proposeGoalSuggestion(accountId:String,projectId:String,req:GoalSuggestionCreateRequest):GoalSuggestionResponse = db.tx { c -> project(c,accountId,projectId);req.parentGoalId?.let { goal(c,accountId,projectId,it) };val title=req.title.trim();if(title.isEmpty()||title.length>200) throw validation("Invalid goal suggestion title");val provenance=req.provenanceJson.trim().ifEmpty { "{}" }.also { if(it.length>20_000) throw validation("Goal suggestion provenance too large") };c.prepareStatement("INSERT INTO goal_suggestion(account_id,project_id,parent_goal_id,title,description,provenance) VALUES (?::uuid,?::uuid,?::uuid,?,?,?::jsonb) RETURNING *").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,req.parentGoalId);ps.setString(4,title);ps.setString(5,req.description?.take(4000));ps.setString(6,provenance);runCatching { ps.executeQuery() }.getOrElse { throw validation("Goal suggestion provenance must be valid JSON") }.use { rs -> rs.next();mapSuggestion(rs) } } }
    fun decideGoalSuggestion(accountId:String,projectId:String,id:String,req:GoalSuggestionDecisionRequest):GoalSuggestionResponse = db.tx { c -> project(c,accountId,projectId);val decision=req.decision.uppercase();if(decision !in setOf("ACCEPT","REJECT")) throw validation("decision must be ACCEPT or REJECT");val current=suggestion(c,accountId,projectId,id);if(current.revision!=req.expectedRevision) throw conflict("Goal suggestion revision conflict");if(current.state!="PROPOSED") throw conflict("Goal suggestion already decided");var acceptedGoal:String?=null;if(decision=="ACCEPT") acceptedGoal=c.prepareStatement("INSERT INTO goal(account_id,project_id,title,description,status,user_created) VALUES (?::uuid,?::uuid,?,?,'ACTIVE',false) RETURNING id").use { ps -> ps.setString(1,accountId);ps.setString(2,projectId);ps.setString(3,current.title);ps.setString(4,current.description);ps.executeQuery().use { rs -> rs.next();rs.getString(1) } };c.prepareStatement("UPDATE goal_suggestion SET state=?,accepted_goal_id=?::uuid,updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND project_id=?::uuid AND revision=? RETURNING *").use { ps -> ps.setString(1,if(decision=="ACCEPT")"ACCEPTED" else "REJECTED");ps.setString(2,acceptedGoal);ps.setString(3,id);ps.setString(4,accountId);ps.setString(5,projectId);ps.setLong(6,req.expectedRevision);ps.executeQuery().use { rs -> if(!rs.next()) throw conflict("Goal suggestion conflict");mapSuggestion(rs) } } }
    fun assessmentHistory(accountId:String,assessmentId:String,limit:Int=50):AssessmentHistoryResponse = db.tx { c -> assessment(c,accountId,assessmentId);val attempts=c.prepareStatement("SELECT id,state,score,started_at,submitted_at,deadline_at,duration_seconds,retest_of_attempt_id,revision FROM assessment_attempt WHERE account_id=?::uuid AND assessment_id=?::uuid ORDER BY created_at DESC LIMIT ?").use { ps -> ps.setString(1,accountId);ps.setString(2,assessmentId);ps.setInt(3,limit.coerceIn(1,200));ps.executeQuery().use { rs -> buildList { while(rs.next()) add(AssessmentAttemptHistoryItemResponse(rs.getString(1),rs.getString(2),rs.getObject(3)?.let{(it as Number).toDouble()},rs.getObject(4,OffsetDateTime::class.java)?.toInstant()?.toString(),rs.getObject(5,OffsetDateTime::class.java)?.toInstant()?.toString(),rs.getObject(6,OffsetDateTime::class.java)?.toInstant()?.toString(),rs.getObject(7)?.let{(it as Number).toInt()},rs.getString(8),rs.getLong(9))) } } };val graded=attempts.filter { it.state=="GRADED" && it.score!=null }.reversed();AssessmentHistoryResponse(assessmentId,attempts,graded.maxOfOrNull{it.score!!},graded.lastOrNull()?.score,if(graded.size>=2) graded.last().score!!-graded.first().score!! else null) }
    fun startRetest(accountId:String,assessmentId:String,req:RetestRequest):RetestResponse = db.tx { c -> val config=assessment(c,accountId,assessmentId);val previous=req.previousAttemptId?.also { attempt(c,accountId,assessmentId,it) };val duration=parseDurationSeconds(config.second);c.prepareStatement("INSERT INTO assessment_attempt(account_id,assessment_id,project_id,state,started_at,last_active_at,duration_seconds,deadline_at,retest_of_attempt_id) SELECT ?::uuid,a.id,a.project_id,'IN_PROGRESS',now(),now(),?,CASE WHEN ?::integer IS NULL THEN NULL ELSE now()+make_interval(secs => ?::integer) END,?::uuid FROM assessment a WHERE a.id=?::uuid AND a.account_id=?::uuid AND a.deleted_at IS NULL RETURNING *").use { ps -> ps.setString(1,accountId);if(duration==null){ps.setObject(2,null);ps.setObject(3,null);ps.setObject(4,null)}else{ps.setInt(2,duration);ps.setInt(3,duration);ps.setInt(4,duration)};ps.setString(5,previous);ps.setString(6,assessmentId);ps.setString(7,accountId);ps.executeQuery().use { rs -> if(!rs.next()) throw notFound("ASSESSMENT_NOT_FOUND","Assessment not found");val attempt=AttemptResponse(rs.getString("id"),rs.getString("assessment_id"),rs.getString("project_id"),rs.getString("state"),null,rs.getLong("revision"));RetestResponse(attempt,rs.getObject("deadline_at",OffsetDateTime::class.java)?.toInstant()?.toString(),rs.getString("retest_of_attempt_id")) } } }
    fun export(accountId:String):AccountExportFinalResponse = db.tx { c -> val profile=c.prepareStatement("SELECT display_name,preferred_language,timezone,onboarding_complete,memory_enabled FROM user_profile WHERE account_id=?::uuid").use { ps -> ps.setString(1,accountId);ps.executeQuery().use { rs -> if(!rs.next()) throw notFound("PROFILE_NOT_FOUND","Profile not found");AccountExportProfile(rs.getString(1),rs.getString(2),rs.getString(3),rs.getBoolean(4),rs.getBoolean(5)) } };val counts=linkedMapOf<String,Long>();val payloads=linkedMapOf<String,String>();for(table in exportTables) { val count=c.prepareStatement("SELECT count(*) FROM $table WHERE account_id=?::uuid").use { ps -> ps.setString(1,accountId);ps.executeQuery().use { rs -> rs.next();rs.getLong(1) } };val json=c.prepareStatement("SELECT COALESCE(jsonb_agg(to_jsonb(x)),'[]'::jsonb)::text FROM (SELECT * FROM $table WHERE account_id=?::uuid ORDER BY 1) x").use { ps -> ps.setString(1,accountId);ps.executeQuery().use { rs -> rs.next();rs.getString(1) } };payloads[table]=json;counts[table]=count };val aliases=linkedMapOf(
            "progressionProfiles" to "progression_profile","xpLedger" to "xp_ledger","coinAccounts" to "coin_account_projection","coinLedger" to "coin_ledger",
            "rewardGrants" to "reward_grant","rewardDecisions" to "reward_decision_log","rewardQueue" to "activity_reward_queue","dailyActivity" to "daily_activity_state",
            "consistencyState" to "consistency_state","consistencyHistory" to "consistency_history","achievementProgress" to "achievement_progress",
            "inventoryOwnership" to "inventory_ownership","equippedAvatars" to "equipped_avatar","storePurchases" to "store_purchase","storeRefunds" to "store_refund",
            "personalMaps" to "personal_map","mapGenerations" to "map_generation_record","mapUnitProgress" to "map_unit_progress","seasonProgress" to "season_progress",
            "gamingStatistics" to "gaming_statistics","gameStateEvents" to "game_state_event"
        );aliases.forEach{(alias,table)->counts[alias]=counts.getValue(table)};val canonical=payloads.entries.joinToString("\n") { it.key+"="+it.value };val digest=sha256(canonical);c.prepareStatement("INSERT INTO account_export_audit(account_id,entity_counts,payload_sha256) VALUES (?::uuid,?::jsonb,?)").use { ps -> ps.setString(1,accountId);ps.setString(2,mapLongJson(counts));ps.setString(3,digest);ps.executeUpdate() };AccountExportFinalResponse(accountId,OffsetDateTime.now(ZoneOffset.UTC).toInstant().toString(),3,profile,counts,payloads,digest) }

    private fun project(c:Connection,a:String,p:String){c.prepareStatement("SELECT 1 FROM project WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,p);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw notFound("PROJECT_NOT_FOUND","Project not found")}}}
    private fun goal(c:Connection,a:String,p:String,g:String){c.prepareStatement("SELECT 1 FROM goal WHERE id=?::uuid AND account_id=?::uuid AND project_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,g);ps.setString(2,a);ps.setString(3,p);ps.executeQuery().use{if(!it.next())throw notFound("GOAL_NOT_FOUND","Goal not found")}}}
    private fun pathExists(c:Connection,a:String,start:String,target:String):Boolean=c.prepareStatement("WITH RECURSIVE walk(goal_id) AS (SELECT depends_on_goal_id FROM goal_dependency WHERE account_id=?::uuid AND goal_id=?::uuid UNION SELECT d.depends_on_goal_id FROM goal_dependency d JOIN walk w ON d.goal_id=w.goal_id WHERE d.account_id=?::uuid) SELECT EXISTS(SELECT 1 FROM walk WHERE goal_id=?::uuid)").use{ps->ps.setString(1,a);ps.setString(2,start);ps.setString(3,a);ps.setString(4,target);ps.executeQuery().use{rs->rs.next();rs.getBoolean(1)}}
    private fun suggestion(c:Connection,a:String,p:String,id:String)=c.prepareStatement("SELECT * FROM goal_suggestion WHERE id=?::uuid AND account_id=?::uuid AND project_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.setString(3,p);ps.executeQuery().use{rs->if(!rs.next())throw notFound("GOAL_SUGGESTION_NOT_FOUND","Goal suggestion not found");mapSuggestion(rs)}}
    private fun mapSuggestion(rs:java.sql.ResultSet)=GoalSuggestionResponse(rs.getString("id"),rs.getString("parent_goal_id"),rs.getString("title"),rs.getString("description"),rs.getString("state"),rs.getString("accepted_goal_id"),rs.getString("provenance"),rs.getLong("revision"),rs.getObject("created_at",OffsetDateTime::class.java).toInstant().toString())
    private fun assessment(c:Connection,a:String,id:String):Pair<String,String> = c.prepareStatement("SELECT project_id,config::text FROM assessment WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw notFound("ASSESSMENT_NOT_FOUND","Assessment not found");(rs.getString(1)?:"") to rs.getString(2)}}
    private fun attempt(c:Connection,a:String,assessment:String,id:String):String=c.prepareStatement("SELECT id FROM assessment_attempt WHERE id=?::uuid AND account_id=?::uuid AND assessment_id=?::uuid AND state='GRADED'").use{ps->ps.setString(1,id);ps.setString(2,a);ps.setString(3,assessment);ps.executeQuery().use{rs->if(!rs.next())throw notFound("ATTEMPT_NOT_FOUND","Graded attempt not found");rs.getString(1)}}
    private fun parseDurationSeconds(json:String):Int?=Regex("\"durationSeconds\"\\s*:\\s*(\\d+)").find(json)?.groupValues?.get(1)?.toIntOrNull()?.takeIf{it in 60..86_400}
    private fun validateGoalLinkObject(c:Connection,a:String,p:String,type:String,id:String){if(type=="SOURCE") { c.prepareStatement("SELECT 1 FROM source s JOIN source_project_link l ON l.source_id=s.id AND l.account_id=s.account_id WHERE s.id=?::uuid AND s.account_id=?::uuid AND l.project_id=?::uuid AND s.deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.setString(3,p);ps.executeQuery().use{if(!it.next())throw notFound("LINK_OBJECT_NOT_FOUND","Linked object not found")}};return };val table=when(type){"NOTE"->"note";"CONVERSATION"->"conversation";"TEST","QUIZ"->"assessment";"PRACTICE"->"practice_session";"FLASHCARD_DECK"->"flashcard_deck";"MISTAKE"->"mistake";else->throw validation("Unsupported goal link type")};val deleted=if(table=="practice_session")"" else " AND deleted_at IS NULL";val kind=if(type in setOf("TEST","QUIZ"))" AND kind=?" else "";c.prepareStatement("SELECT 1 FROM $table WHERE id=?::uuid AND account_id=?::uuid AND project_id=?::uuid$kind$deleted").use{ps->ps.setString(1,id);ps.setString(2,a);ps.setString(3,p);if(type in setOf("TEST","QUIZ"))ps.setString(4,type);ps.executeQuery().use{if(!it.next())throw notFound("LINK_OBJECT_NOT_FOUND","Linked object not found")}}}
    private fun mapLongJson(m:Map<String,Long>)="{"+m.entries.joinToString(","){"\"${it.key}\":${it.value}"}+"}"
    private fun conflict(message:String)=DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,message))
    private fun notFound(code:String,message:String)=DomainException(DomainError(code,ErrorCategory.NOT_FOUND,message))
    companion object { private val exportTables=listOf("project","goal","project_instruction","conversation","conversation_message","message_attachment","assistant_message_citation","source","source_version","source_chunk","source_project_link","source_collection","annotation","note","note_version","assessment","assessment_question","assessment_attempt","assessment_answer","assessment_comparison","practice_session","practice_item","practice_attempt","practice_hint","practice_feedback","flashcard_deck","flashcard","flashcard_schedule","flashcard_review","mistake","learning_signal","memory_item","memory_evidence","student_signal","student_signal_evidence","personalization_recommendation","context_carry_state","source_relationship","progression_profile","xp_ledger","coin_account_projection","coin_ledger","reward_grant","reward_decision_log","activity_reward_queue","daily_activity_state","consistency_state","consistency_history","achievement_progress","inventory_ownership","equipped_avatar","store_purchase","store_refund","personal_map","map_generation_record","map_unit_progress","season_progress","gaming_statistics","game_state_event","frontend_semantic_event","qualified_active_day","map_checkpoint_reward","notification_preference","user_setting","activity_event","generated_artifact","translation_record","goal_dependency","goal_link","goal_suggestion","account_external_identity") }
}

class AccountDeletionWorker(private val db:Database, enabled:Boolean):AutoCloseable {
    private val executor=java.util.concurrent.Executors.newSingleThreadScheduledExecutor { r -> Thread(r,"account-deletion-worker").apply{isDaemon=true} }
    init { if(enabled) executor.scheduleWithFixedDelay({ runCatching{purgeDue(10)} },5,60,java.util.concurrent.TimeUnit.SECONDS) }
    fun purgeDue(limit:Int):Int { var purged=0;repeat(limit.coerceIn(1,100)) { val did=db.tx { c -> val row=c.prepareStatement("SELECT request_id,account_id FROM account_deletion_lifecycle WHERE state IN ('PURGE_PENDING','FAILED_RETRYABLE') AND purge_after<=now() AND account_id IS NOT NULL ORDER BY purge_after FOR UPDATE SKIP LOCKED LIMIT 1").use { ps -> ps.executeQuery().use { rs -> if(rs.next()) rs.getString(1) to rs.getString(2) else null } } ?: return@tx false;c.prepareStatement("UPDATE account_deletion_lifecycle SET state='PURGING',started_at=COALESCE(started_at,now()),updated_at=now() WHERE request_id=?::uuid").use { ps -> ps.setString(1,row.first);ps.executeUpdate() };c.prepareStatement("DELETE FROM account WHERE id=?::uuid").use { ps -> ps.setString(1,row.second);ps.executeUpdate() };c.prepareStatement("UPDATE account_deletion_lifecycle SET account_id=NULL,state='PURGED',completed_at=now(),updated_at=now(),last_error_code=NULL WHERE request_id=?::uuid").use { ps -> ps.setString(1,row.first);ps.executeUpdate() };true };if(!did) return purged;purged++ };return purged }
    override fun close(){executor.shutdownNow()}
}
