package com.veltrix.hom.vnext.server

import com.veltrix.hom.vnext.core.*
import java.sql.Connection
import java.sql.ResultSet
import java.time.Instant
import java.time.OffsetDateTime

class PracticeRepository(private val db:Database){
    fun create(accountId:String,req:CreatePracticeRequest):PracticeResponse=db.tx{c->req.projectId?.let{requireOwned(c,"project",accountId,it)};req.targetMistakeId?.let{requireOwned(c,"mistake",accountId,it)};c.prepareStatement("INSERT INTO practice_session(account_id,project_id,focus_topic,target_mistake_id,state) VALUES (?::uuid,?::uuid,?,?::uuid,'IN_PROGRESS') RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,req.projectId);ps.setString(3,req.focusTopic?.take(200));ps.setString(4,req.targetMistakeId);ps.executeQuery().use{rs->rs.next();map(rs)}}}
    fun complete(accountId:String,id:String,expectedRevision:Long):PracticeResponse=db.tx{c->val current=get(c,accountId,id);if(current.revision!=expectedRevision)throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Practice revision conflict"));if(current.state!="IN_PROGRESS")throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Practice already completed"));c.prepareStatement("UPDATE practice_session SET state='COMPLETED',updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND revision=? RETURNING *").use{ps->ps.setString(1,id);ps.setString(2,accountId);ps.setLong(3,expectedRevision);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Practice conflict"));val next=map(rs);insertActivity(c,accountId,"PRACTICE_COMPLETED",next.projectId,id,"practice-complete:$id",true);next}}}
    private fun get(c:Connection,a:String,id:String)=c.prepareStatement("SELECT * FROM practice_session WHERE id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("PRACTICE_NOT_FOUND",ErrorCategory.NOT_FOUND,"Practice not found"));map(rs)}}
    private fun requireOwned(c:Connection,t:String,a:String,id:String){require(t in setOf("project","mistake"));c.prepareStatement("SELECT 1 FROM $t WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("NOT_FOUND",ErrorCategory.NOT_FOUND,"Linked object not found"))}}}
    private fun map(rs:ResultSet)=PracticeResponse(rs.uuid("id"),rs.uuidOrNull("project_id"),rs.getString("focus_topic"),rs.uuidOrNull("target_mistake_id"),rs.getString("state"),rs.getLong("revision"))
}

class FlashcardRepository(private val db:Database){
    fun createDeck(accountId:String,req:CreateDeckRequest):DeckResponse=db.tx{c->if(req.title.trim().isEmpty())throw validation("Deck title required");req.projectId?.let{owned(c,"project",accountId,it)};req.sourceId?.let{owned(c,"source",accountId,it)};c.prepareStatement("INSERT INTO flashcard_deck(account_id,project_id,source_id,scope,title) VALUES (?::uuid,?::uuid,?::uuid,?,?) RETURNING *").use{ps->ps.setString(1,accountId);ps.setString(2,req.projectId);ps.setString(3,req.sourceId);ps.setString(4,req.scope.take(40));ps.setString(5,req.title.trim().take(240));ps.executeQuery().use{rs->rs.next();mapDeck(rs)}}}
    fun createCard(accountId:String,deckId:String,req:CreateCardRequest):CardResponse=db.tx{c->val deck=deck(c,accountId,deckId);if(req.front.trim().isEmpty()||req.back.trim().isEmpty())throw validation("Card front/back required");val project=req.projectId?:deck.projectId;project?.let{owned(c,"project",accountId,it)};val cardId=c.prepareStatement("INSERT INTO flashcard(account_id,deck_id,project_id,front,back,explanation) VALUES (?::uuid,?::uuid,?::uuid,?,?,?) RETURNING id,revision").use{ps->ps.setString(1,accountId);ps.setString(2,deckId);ps.setString(3,project);ps.setString(4,req.front.trim());ps.setString(5,req.back.trim());ps.setString(6,req.explanation);ps.executeQuery().use{rs->rs.next();rs.uuid("id") to rs.getLong("revision")}};c.prepareStatement("INSERT INTO flashcard_schedule(card_id,account_id) VALUES (?::uuid,?::uuid)").use{ps->ps.setString(1,cardId.first);ps.setString(2,accountId);ps.executeUpdate()};getCard(c,accountId,cardId.first)}
    fun due(accountId:String,limit:Int=100):List<CardResponse> =db.tx{c->c.prepareStatement("SELECT f.*,s.interval_days,s.repetitions,s.lapses,s.due_at FROM flashcard f JOIN flashcard_schedule s ON s.card_id=f.id WHERE f.account_id=?::uuid AND f.deleted_at IS NULL AND f.suspended=false AND s.due_at<=now() ORDER BY s.due_at,f.id LIMIT ?").use{ps->ps.setString(1,accountId);ps.setInt(2,limit.coerceIn(1,200));ps.executeQuery().use{rs->buildList{while(rs.next())add(mapCard(rs))}}}}
    fun review(accountId:String,cardId:String,req:ReviewCardRequest):CardResponse=db.tx{c->val current=getCard(c,accountId,cardId);val full=c.prepareStatement("SELECT interval_days,ease,repetitions,lapses,due_at,last_reviewed_at,revision FROM flashcard_schedule WHERE card_id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,cardId);ps.setString(2,accountId);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CARD_NOT_FOUND",ErrorCategory.NOT_FOUND,"Card schedule not found"));FlashcardScheduleState(cardId,rs.getInt(1),rs.getDouble(2),rs.getInt(3),rs.getInt(4),rs.getObject(5,OffsetDateTime::class.java).toInstant(),rs.getObject(6,OffsetDateTime::class.java)?.toInstant()) to rs.getLong(7)}};val rating=runCatching{ReviewRating.valueOf(req.rating.uppercase())}.getOrElse{throw validation("Invalid review rating")};val next=FlashcardScheduler.review(full.first,rating,Instant.now());c.prepareStatement("UPDATE flashcard_schedule SET interval_days=?,ease=?,repetitions=?,lapses=?,due_at=?,last_reviewed_at=?,revision=revision+1 WHERE card_id=?::uuid AND account_id=?::uuid AND revision=?").use{ps->ps.setInt(1,next.intervalDays);ps.setDouble(2,next.ease);ps.setInt(3,next.repetitions);ps.setInt(4,next.lapses);ps.setObject(5,OffsetDateTime.ofInstant(next.dueAt,java.time.ZoneOffset.UTC));ps.setObject(6,OffsetDateTime.ofInstant(next.lastReviewedAt?:Instant.now(),java.time.ZoneOffset.UTC));ps.setString(7,cardId);ps.setString(8,accountId);ps.setLong(9,full.second);if(ps.executeUpdate()!=1)throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Flashcard schedule conflict"))};c.prepareStatement("INSERT INTO flashcard_review(account_id,card_id,rating,previous_state,next_state) VALUES (?::uuid,?::uuid,?,?::jsonb,?::jsonb)").use{ps->ps.setString(1,accountId);ps.setString(2,cardId);ps.setString(3,rating.name);ps.setString(4,scheduleJson(full.first));ps.setString(5,scheduleJson(next));ps.executeUpdate()};insertActivity(c,accountId,"FLASHCARD_REVIEW_COMPLETED",current.projectId,cardId,"flashcard-review:${cardId}:${(next.lastReviewedAt?:Instant.now()).toEpochMilli()}",true);getCard(c,accountId,cardId)}
    private fun deck(c:Connection,a:String,id:String):DeckResponse=c.prepareStatement("SELECT * FROM flashcard_deck WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("DECK_NOT_FOUND",ErrorCategory.NOT_FOUND,"Deck not found"));mapDeck(rs)}}
    private fun getCard(c:Connection,a:String,id:String):CardResponse=c.prepareStatement("SELECT f.*,s.interval_days,s.repetitions,s.lapses,s.due_at FROM flashcard f JOIN flashcard_schedule s ON s.card_id=f.id WHERE f.id=?::uuid AND f.account_id=?::uuid AND f.deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CARD_NOT_FOUND",ErrorCategory.NOT_FOUND,"Card not found"));mapCard(rs)}}
    private fun owned(c:Connection,t:String,a:String,id:String){require(t in setOf("project","source"));c.prepareStatement("SELECT 1 FROM $t WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("NOT_FOUND",ErrorCategory.NOT_FOUND,"Linked object not found"))}}}
    private fun mapDeck(rs:ResultSet)=DeckResponse(rs.uuid("id"),rs.getString("title"),rs.getString("scope"),rs.uuidOrNull("project_id"),rs.uuidOrNull("source_id"),rs.getLong("revision"))
    private fun mapCard(rs:ResultSet)=CardResponse(rs.uuid("id"),rs.uuid("deck_id"),rs.uuidOrNull("project_id"),rs.getString("front"),rs.getString("back"),rs.getString("explanation"),rs.instant("due_at"),rs.getInt("interval_days"),rs.getInt("repetitions"),rs.getInt("lapses"),rs.getLong("revision"))
}

class MistakeRepository(private val db:Database){
    fun list(accountId:String,projectId:String?=null,limit:Int=100):List<MistakeResponse> =db.tx{c->val sql="SELECT * FROM mistake WHERE account_id=?::uuid AND deleted_at IS NULL"+(if(projectId!=null)" AND project_id=?::uuid" else "")+" ORDER BY (status='ACTIVE') DESC,last_seen_at DESC LIMIT ?";c.prepareStatement(sql).use{ps->var i=1;ps.setString(i++,accountId);if(projectId!=null)ps.setString(i++,projectId);ps.setInt(i,limit.coerceIn(1,200));ps.executeQuery().use{rs->buildList{while(rs.next())add(map(rs))}}}}
    fun resolve(accountId:String,id:String,expectedRevision:Long):MistakeResponse=db.tx{c->c.prepareStatement("UPDATE mistake SET status='RESOLVED',revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND revision=? AND deleted_at IS NULL RETURNING *").use{ps->ps.setString(1,id);ps.setString(2,accountId);ps.setLong(3,expectedRevision);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Mistake revision conflict or not found"));val m=map(rs);insertActivity(c,accountId,"MISTAKE_RESOLVED",m.projectId,id,"mistake-resolved:$id:$expectedRevision",true);m}}}
    private fun map(rs:ResultSet)=MistakeResponse(rs.uuid("id"),rs.uuidOrNull("project_id"),rs.uuidOrNull("source_id"),rs.getString("topic"),rs.getString("prompt"),rs.getString("user_answer"),rs.getString("expected_answer"),rs.getInt("occurrence_count"),rs.getString("status"),rs.getLong("revision"))
}
