package com.veltrix.hom.vnext.server.learning

import com.veltrix.hom.vnext.core.*
import com.veltrix.hom.vnext.server.*
import java.sql.Connection
import java.sql.ResultSet
import java.util.UUID

class DeepPracticeRepository(private val db:Database){
    fun create(accountId:String,req:PracticeConfigRequest):PracticeSessionDetailResponse=db.tx{c->
        req.projectId?.let{owned(c,"project",accountId,it)}; req.targetMistakeId?.let{owned(c,"mistake",accountId,it)}
        req.sourceIds.forEach{owned(c,"source",accountId,it)}
        require(req.difficulty in 1..5);require(req.targetItemCount in 1..100)
        val id=c.prepareStatement("INSERT INTO practice_session(account_id,project_id,focus_topic,source_ids,target_mistake_id,state,difficulty,target_item_count,adaptive,hint_policy,reveal_policy,current_position) VALUES (?::uuid,?::uuid,?,?::jsonb,?::uuid,'IN_PROGRESS',?,?,?,?,?,0) RETURNING id").use{ps->ps.setString(1,accountId);ps.setString(2,req.projectId);ps.setString(3,req.focusTopic?.take(200));ps.setString(4,jsonArray(req.sourceIds));ps.setString(5,req.targetMistakeId);ps.setInt(6,req.difficulty);ps.setInt(7,req.targetItemCount);ps.setBoolean(8,req.adaptive);ps.setString(9,req.hintPolicy);ps.setString(10,req.revealPolicy);ps.executeQuery().use{rs->rs.next();rs.getString(1)}}
        detail(c,accountId,id)
    }
    fun detail(accountId:String,id:String):PracticeSessionDetailResponse=db.tx{c->detail(c,accountId,id)}
    fun addItem(accountId:String,sessionId:String,req:PracticeSeedItemRequest):PracticeItemResponse=db.tx{c->
        val s=session(c,accountId,sessionId);if(s.state!="IN_PROGRESS")badState();require(req.prompt.trim().isNotEmpty());require(req.expectedAnswer.trim().isNotEmpty());require(req.difficulty in 1..5)
        val pos=c.prepareStatement("SELECT coalesce(max(position),-1)+1 FROM practice_item WHERE session_id=?::uuid").use{ps->ps.setString(1,sessionId);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}}
        val state=if(pos==s.currentPosition)"ACTIVE" else "PENDING"
        c.prepareStatement("INSERT INTO practice_item(session_id,account_id,position,prompt,validator,state,item_type,expected_answer,explanation,difficulty,topic) VALUES (?::uuid,?::uuid,?,?, '{}'::jsonb,?,?,?,?,?,?) RETURNING *").use{ps->ps.setString(1,sessionId);ps.setString(2,accountId);ps.setInt(3,pos);ps.setString(4,req.prompt.trim());ps.setString(5,state);ps.setString(6,req.itemType);ps.setString(7,req.expectedAnswer.trim());ps.setString(8,req.explanation);ps.setInt(9,req.difficulty);ps.setString(10,req.topic?.take(200));ps.executeQuery().use{rs->rs.next();mapItem(rs)}}
    }
    fun attempt(accountId:String,sessionId:String,itemId:String,req:PracticeAttemptRequest):PracticeAttemptResponse=db.tx{c->
        val s=session(c,accountId,sessionId);if(s.state!="IN_PROGRESS")badState(); val item=item(c,accountId,sessionId,itemId);if(item.state !in setOf("ACTIVE","ANSWERED","CHECKED"))badState()
        if(req.idempotencyKey.length !in 8..180)throw validation("Invalid idempotency key")
        val existing=c.prepareStatement("SELECT id,attempt_number,answer,correct,score FROM practice_attempt WHERE account_id=?::uuid AND item_id=?::uuid AND answer=? ORDER BY created_at DESC LIMIT 1").use{ps->ps.setString(1,accountId);ps.setString(2,itemId);ps.setString(3,req.answer);ps.executeQuery().use{rs->if(rs.next())PracticeAttemptResponse(rs.getString(1),itemId,rs.getInt(2),rs.getString(3),rs.getObject(4) as? Boolean,rs.getObject(5)?.let{rs.getDouble(5)}) else null}}
        existing ?: run {val n=c.prepareStatement("SELECT coalesce(max(attempt_number),0)+1 FROM practice_attempt WHERE item_id=?::uuid").use{ps->ps.setString(1,itemId);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}}; val id=c.prepareStatement("INSERT INTO practice_attempt(account_id,session_id,item_id,answer,attempt_number) VALUES (?::uuid,?::uuid,?::uuid,?,?) RETURNING id").use{ps->ps.setString(1,accountId);ps.setString(2,sessionId);ps.setString(3,itemId);ps.setString(4,req.answer.take(10000));ps.setInt(5,n);ps.executeQuery().use{rs->rs.next();rs.getString(1)}};c.prepareStatement("UPDATE practice_item SET user_answer=?,state='ANSWERED',updated_at=now(),revision=revision+1 WHERE id=?::uuid").use{ps->ps.setString(1,req.answer.take(10000));ps.setString(2,itemId);ps.executeUpdate()};PracticeAttemptResponse(id,itemId,n,req.answer,null,null)}
    }
    fun hint(accountId:String,sessionId:String,itemId:String):PracticeHintResponse=db.tx{c->
        session(c,accountId,sessionId);val i=item(c,accountId,sessionId,itemId);val count=c.prepareStatement("SELECT count(*) FROM practice_hint WHERE item_id=?::uuid").use{ps->ps.setString(1,itemId);ps.executeQuery().use{rs->rs.next();rs.getInt(1)}};val body=deterministicHint(i.prompt,i.expectedAnswer ?: badState(),count);c.prepareStatement("INSERT INTO practice_hint(account_id,session_id,item_id,hint_index,body) VALUES (?::uuid,?::uuid,?::uuid,?,?) ON CONFLICT(item_id,hint_index) DO UPDATE SET body=excluded.body RETURNING hint_index,body").use{ps->ps.setString(1,accountId);ps.setString(2,sessionId);ps.setString(3,itemId);ps.setInt(4,count);ps.setString(5,body);ps.executeQuery().use{rs->rs.next();PracticeHintResponse(itemId,rs.getInt(1),rs.getString(2))}}
    }
    fun check(accountId:String,sessionId:String,itemId:String):PracticeCheckResponse=db.tx{c->
        val s=session(c,accountId,sessionId);if(s.state!="IN_PROGRESS")badState();val i=item(c,accountId,sessionId,itemId);val ans=i.userAnswer?:throw DomainException(DomainError("PRACTICE_STATE_INVALID",ErrorCategory.CONFLICT,"Attempt required before check"));val expected=i.expectedAnswer?:throw DomainException(DomainError("PRACTICE_STATE_INVALID",ErrorCategory.CONFLICT,"Expected answer unavailable"));val correct=normalize(ans)==normalize(expected);val score=if(correct)1.0 else 0.0
        val attemptId=c.prepareStatement("SELECT id FROM practice_attempt WHERE item_id=?::uuid ORDER BY attempt_number DESC LIMIT 1").use{ps->ps.setString(1,itemId);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("PRACTICE_STATE_INVALID",ErrorCategory.CONFLICT,"Attempt missing"));rs.getString(1)}}
        c.prepareStatement("UPDATE practice_attempt SET correct=?,score=? WHERE id=?::uuid").use{ps->ps.setBoolean(1,correct);ps.setDouble(2,score);ps.setString(3,attemptId);ps.executeUpdate()}
        c.prepareStatement("INSERT INTO practice_feedback(account_id,session_id,item_id,attempt_id,correct,score,explanation) VALUES (?::uuid,?::uuid,?::uuid,?::uuid,?,?,?) ON CONFLICT(attempt_id) DO UPDATE SET correct=excluded.correct,score=excluded.score,explanation=excluded.explanation").use{ps->ps.setString(1,accountId);ps.setString(2,sessionId);ps.setString(3,itemId);ps.setString(4,attemptId);ps.setBoolean(5,correct);ps.setDouble(6,score);ps.setString(7,i.explanation.ifBlank{if(correct)"Correct." else "Expected: $expected"});ps.executeUpdate()}
        c.prepareStatement("UPDATE practice_item SET state='COMPLETED',updated_at=now(),revision=revision+1 WHERE id=?::uuid").use{ps->ps.setString(1,itemId);ps.executeUpdate()}
        val mistakeId=if(correct)null else aggregateMistake(c,accountId,s.projectId,i.topic?:s.focusTopic?:"practice",i.prompt,ans,expected)
        insertSignal(c,accountId,s.projectId,i.topic?:s.focusTopic?:"practice",if(correct)"PRACTICE_CORRECT" else "PRACTICE_WEAKNESS",if(correct)1.0 else -1.0,itemId)
        val next=activateNext(c,accountId,s,i.position)
        PracticeCheckResponse(item(c,accountId,sessionId,itemId).let{mapItem(it)},correct,score,i.explanation.ifBlank{if(correct)"Correct." else "Expected: $expected"},next,mistakeId)
    }
    fun complete(accountId:String,id:String,expectedRevision:Long):PracticeCompleteResponse=db.tx{c->
        val s=session(c,accountId,id);if(s.revision!=expectedRevision)throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Practice revision conflict"));val stats=c.prepareStatement("SELECT count(*) FILTER(WHERE state='COMPLETED'),count(*) FILTER(WHERE state='COMPLETED' AND EXISTS(SELECT 1 FROM practice_attempt pa WHERE pa.item_id=practice_item.id AND pa.correct=true)) FROM practice_item WHERE session_id=?::uuid").use{ps->ps.setString(1,id);ps.executeQuery().use{rs->rs.next();rs.getInt(1) to rs.getInt(2)}};val acc=if(stats.first==0)0.0 else stats.second.toDouble()/stats.first;val summary="{\"answered\":${stats.first},\"correct\":${stats.second},\"accuracy\":${"%.4f".format(java.util.Locale.ROOT,acc)}}";c.prepareStatement("UPDATE practice_session SET state='COMPLETED',completed_at=now(),summary=?::jsonb,updated_at=now(),revision=revision+1 WHERE id=?::uuid AND account_id=?::uuid AND revision=? RETURNING *").use{ps->ps.setString(1,summary);ps.setString(2,id);ps.setString(3,accountId);ps.setLong(4,expectedRevision);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("CONFLICT",ErrorCategory.CONFLICT,"Practice conflict"));val p=mapSession(SessionRow(rs));insertActivity(c,accountId,"PRACTICE_COMPLETED",p.projectId,id,"practice-complete:$id",true);PracticeCompleteResponse(p,stats.first,stats.second,acc,summary)}}
    }
    fun skip(accountId:String,sessionId:String,itemId:String):PracticeSessionDetailResponse=db.tx{c->val s=session(c,accountId,sessionId);val i=item(c,accountId,sessionId,itemId);c.prepareStatement("UPDATE practice_item SET state='SKIPPED',updated_at=now(),revision=revision+1 WHERE id=?::uuid").use{ps->ps.setString(1,itemId);ps.executeUpdate()};activateNext(c,accountId,s,i.position);detail(c,accountId,sessionId)}

    private fun detail(c:Connection,a:String,id:String):PracticeSessionDetailResponse{val s=session(c,a,id);val items=c.prepareStatement("SELECT * FROM practice_item WHERE session_id=?::uuid AND account_id=?::uuid ORDER BY position").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->buildList{while(rs.next())add(mapItem(rs))}}};return PracticeSessionDetailResponse(mapSession(s),s.currentPosition,s.targetItemCount,s.difficulty,s.adaptive,s.hintPolicy,s.revealPolicy,items,s.summary)}
    private fun session(c:Connection,a:String,id:String):SessionRow=c.prepareStatement("SELECT * FROM practice_session WHERE id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("PRACTICE_NOT_FOUND",ErrorCategory.NOT_FOUND,"Practice not found"));SessionRow(rs)}}
    private fun item(c:Connection,a:String,sid:String,id:String):ItemRow=c.prepareStatement("SELECT * FROM practice_item WHERE id=?::uuid AND session_id=?::uuid AND account_id=?::uuid").use{ps->ps.setString(1,id);ps.setString(2,sid);ps.setString(3,a);ps.executeQuery().use{rs->if(!rs.next())throw DomainException(DomainError("PRACTICE_STATE_INVALID",ErrorCategory.NOT_FOUND,"Practice item not found"));ItemRow(rs)}}
    private fun activateNext(c:Connection,a:String,s:SessionRow,pos:Int):String?{val next=c.prepareStatement("SELECT id,position FROM practice_item WHERE session_id=?::uuid AND account_id=?::uuid AND position>? AND state='PENDING' ORDER BY position LIMIT 1").use{ps->ps.setString(1,s.id);ps.setString(2,a);ps.setInt(3,pos);ps.executeQuery().use{rs->if(rs.next())rs.getString(1) to rs.getInt(2) else null}};if(next!=null){c.prepareStatement("UPDATE practice_item SET state='ACTIVE',updated_at=now() WHERE id=?::uuid").use{ps->ps.setString(1,next.first);ps.executeUpdate()};c.prepareStatement("UPDATE practice_session SET current_position=?,updated_at=now(),revision=revision+1 WHERE id=?::uuid").use{ps->ps.setInt(1,next.second);ps.setString(2,s.id);ps.executeUpdate()}};return next?.first}
    private fun aggregateMistake(c:Connection,a:String,p:String?,topic:String,prompt:String,user:String,expected:String):String{val existing=c.prepareStatement("SELECT id FROM mistake WHERE account_id=?::uuid AND project_id IS NOT DISTINCT FROM ?::uuid AND lower(topic)=lower(?) AND lower(prompt)=lower(?) AND deleted_at IS NULL LIMIT 1").use{ps->ps.setString(1,a);ps.setString(2,p);ps.setString(3,topic);ps.setString(4,prompt);ps.executeQuery().use{rs->if(rs.next())rs.getString(1) else null}};return if(existing!=null){c.prepareStatement("UPDATE mistake SET occurrence_count=occurrence_count+1,last_seen_at=now(),status='ACTIVE',user_answer=?,expected_answer=?,revision=revision+1 WHERE id=?::uuid RETURNING id").use{ps->ps.setString(1,user);ps.setString(2,expected);ps.setString(3,existing);ps.executeQuery().use{rs->rs.next();rs.getString(1)}}}else c.prepareStatement("INSERT INTO mistake(account_id,project_id,topic,prompt,user_answer,expected_answer,status) VALUES (?::uuid,?::uuid,?,?,?,?,'ACTIVE') RETURNING id").use{ps->ps.setString(1,a);ps.setString(2,p);ps.setString(3,topic.take(200));ps.setString(4,prompt);ps.setString(5,user);ps.setString(6,expected);ps.executeQuery().use{rs->rs.next();rs.getString(1)}}}
    private fun insertSignal(c:Connection,a:String,p:String?,topic:String,kind:String,value:Double,evidence:String){c.prepareStatement("INSERT INTO learning_signal(account_id,project_id,topic,kind,signal_value,confidence,evidence_ids) VALUES (?::uuid,?::uuid,?,?,?,?,jsonb_build_array(?::text))").use{ps->ps.setString(1,a);ps.setString(2,p);ps.setString(3,topic.take(200));ps.setString(4,kind);ps.setDouble(5,value);ps.setDouble(6,0.9);ps.setString(7,evidence);ps.executeUpdate()}}
    private fun owned(c:Connection,t:String,a:String,id:String){require(t in setOf("project","mistake","source"));c.prepareStatement("SELECT 1 FROM $t WHERE id=?::uuid AND account_id=?::uuid AND deleted_at IS NULL").use{ps->ps.setString(1,id);ps.setString(2,a);ps.executeQuery().use{if(!it.next())throw DomainException(DomainError("NOT_FOUND",ErrorCategory.NOT_FOUND,"Linked object not found"))}}}
    private fun deterministicHint(prompt:String,expected:String,n:Int)=when(n){0->"Focus on the key relation in: ${prompt.take(120)}";1->"The answer begins with '${expected.take(1)}' and has ${expected.length} character(s).";else->"Compare your attempt carefully with the expected form; no full answer reveal before check."}
    private fun normalize(v:String)=v.trim().lowercase().replace(Regex("\\s+")," ")
    private fun badState():Nothing=throw DomainException(DomainError("PRACTICE_STATE_INVALID",ErrorCategory.CONFLICT,"Practice state does not allow this action"))
    private fun jsonArray(v:List<String>)="["+v.joinToString(","){"\"${it.replace("\\","\\\\").replace("\"","\\\"")}\""}+"]"
    private fun mapSession(r:SessionRow)=PracticeResponse(r.id,r.projectId,r.focusTopic,r.targetMistakeId,r.state,r.revision)
    private fun mapItem(r:ItemRow)=PracticeItemResponse(r.id,r.sessionId,r.position,r.prompt,r.itemType,r.state,r.difficulty,r.topic,r.userAnswer,r.revision)
    private fun mapItem(rs:ResultSet)=mapItem(ItemRow(rs))
    private data class SessionRow(val id:String,val projectId:String?,val focusTopic:String?,val targetMistakeId:String?,val state:String,val revision:Long,val currentPosition:Int,val targetItemCount:Int,val difficulty:Int,val adaptive:Boolean,val hintPolicy:String,val revealPolicy:String,val summary:String){constructor(rs:ResultSet):this(rs.getString("id"),rs.getObject("project_id")?.toString(),rs.getString("focus_topic"),rs.getObject("target_mistake_id")?.toString(),rs.getString("state"),rs.getLong("revision"),rs.getInt("current_position"),rs.getInt("target_item_count"),rs.getInt("difficulty"),rs.getBoolean("adaptive"),rs.getString("hint_policy"),rs.getString("reveal_policy"),rs.getString("summary"))}
    private data class ItemRow(val id:String,val sessionId:String,val position:Int,val prompt:String,val itemType:String,val state:String,val difficulty:Int,val topic:String?,val userAnswer:String?,val expectedAnswer:String?,val explanation:String,val revision:Long){constructor(rs:ResultSet):this(rs.getString("id"),rs.getString("session_id"),rs.getInt("position"),rs.getString("prompt"),rs.getString("item_type"),rs.getString("state"),rs.getInt("difficulty"),rs.getString("topic"),rs.getString("user_answer"),rs.getString("expected_answer"),rs.getString("explanation")?:"",rs.getLong("revision"))}
}
